(ns analytics
  (:require [orders :refer :all :as ord]
            [inventory :refer :all :as inv]
            [catalog :refer :all :as cat]
            [billing :refer :all]
            [shipping :refer :all :as ship]))

^{:line 15 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (defrecord PeriodMetric [period metric-name value])

(defn periodmetric-period [r] (:period r))

(defn periodmetric-metric-name [r] (:metric-name r))

(defn periodmetric-value [r] (:value r))

^{:line 18 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (defrecord TrendResult [metric-name direction change-pct])

(defn trendresult-metric-name [r] (:metric-name r))

(defn trendresult-direction [r] (:direction r))

(defn trendresult-change-pct [r] (:change-pct r))

^{:line 21 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (defrecord Bucket [label count total])

(defn bucket-label [r] (:label r))

(defn bucket-count [r] (:count r))

(defn bucket-total [r] (:total r))

^{:line 28 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (defn make-period-metric [period metric-name value]
  ^{:line 30 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (->PeriodMetric period metric-name value))

^{:line 33 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (defn metrics-for-period [metrics period]
  ^{:line 34 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (filterv ^{:line 34 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (fn [m] ^{:line 34 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (= ^{:line 34 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (periodmetric-period m) period)) metrics))

^{:line 38 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (defn metric-values [metrics metric-name]
  ^{:line 39 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (let [matching ^{:line 39 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (filterv ^{:line 39 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (fn [m] ^{:line 39 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (= ^{:line 39 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (periodmetric-metric-name m) metric-name)) metrics)
   sorted ^{:line 41 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (sort-by periodmetric-period matching)]
  ^{:line 42 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (mapv periodmetric-value sorted)))

^{:line 46 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (defn latest-metric [metrics metric-name]
  ^{:line 47 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (let [matching ^{:line 47 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (filterv ^{:line 47 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (fn [m] ^{:line 47 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (= ^{:line 47 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (periodmetric-metric-name m) metric-name)) metrics)
   sorted ^{:line 49 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (sort-by periodmetric-period matching)]
  ^{:line 50 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (if ^{:line 50 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (empty? sorted) nil ^{:line 52 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (last sorted))))

^{:line 56 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (defn earliest-metric [metrics metric-name]
  ^{:line 57 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (let [matching ^{:line 57 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (filterv ^{:line 57 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (fn [m] ^{:line 57 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (= ^{:line 57 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (periodmetric-metric-name m) metric-name)) metrics)
   sorted ^{:line 59 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (sort-by periodmetric-period matching)]
  ^{:line 60 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (if ^{:line 60 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (empty? sorted) nil ^{:line 62 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (first sorted))))

^{:line 65 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (defn metric-count [metrics metric-name]
  ^{:line 66 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (count ^{:line 66 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (filterv ^{:line 66 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (fn [m] ^{:line 66 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (= ^{:line 66 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (periodmetric-metric-name m) metric-name)) metrics)))

^{:line 70 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (defn metric-sum [metrics metric-name]
  ^{:line 71 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (reduce ^{:line 71 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (fn [acc v] ^{:line 71 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (+ acc v)) 0 ^{:line 71 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (metric-values metrics metric-name)))

^{:line 75 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (defn metric-avg [metrics metric-name]
  ^{:line 76 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (let [vals ^{:line 76 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (metric-values metrics metric-name)
   cnt ^{:line 77 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (count vals)]
  ^{:line 78 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (if ^{:line 78 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (= cnt 0) 0 ^{:line 80 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (quot ^{:line 80 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (reduce ^{:line 80 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (fn [acc v] ^{:line 80 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (+ acc v)) 0 vals) cnt))))

^{:line 84 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (defn metric-max [metrics metric-name]
  ^{:line 85 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (let [vals ^{:line 85 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (metric-values metrics metric-name)]
  ^{:line 86 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (if ^{:line 86 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (empty? vals) 0 ^{:line 88 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (reduce ^{:line 88 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (fn [best v] ^{:line 88 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (if ^{:line 88 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (> v best) v best)) ^{:line 89 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (first vals) ^{:line 89 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (rest vals)))))

^{:line 93 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (defn metric-min [metrics metric-name]
  ^{:line 94 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (let [vals ^{:line 94 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (metric-values metrics metric-name)]
  ^{:line 95 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (if ^{:line 95 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (empty? vals) 0 ^{:line 97 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (reduce ^{:line 97 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (fn [best v] ^{:line 97 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (if ^{:line 97 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (< v best) v best)) ^{:line 98 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (first vals) ^{:line 98 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (rest vals)))))

^{:line 101 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (defn all-metric-names [metrics]
  ^{:line 102 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (distinct ^{:line 102 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (mapv periodmetric-metric-name metrics)))

^{:line 105 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (defn all-periods [metrics]
  ^{:line 106 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (distinct ^{:line 106 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (mapv periodmetric-period metrics)))

^{:line 115 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (defn revenue-by-period [orders periods]
  ^{:line 116 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (mapv ^{:line 116 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (fn [p] ^{:line 117 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (let [start ^{:line 117 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (first p)
   end ^{:line 118 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (second p)
   label ^{:line 119 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (nth p 2)
   period-orders ^{:line 120 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (ord/orders-in-period orders start end)
   rev ^{:line 121 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (ord/total-revenue period-orders)]
  ^{:line 122 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (->PeriodMetric label "revenue" rev))) periods))

^{:line 127 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (defn order-count-by-period [orders periods]
  ^{:line 128 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (mapv ^{:line 128 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (fn [p] ^{:line 129 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (let [start ^{:line 129 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (first p)
   end ^{:line 130 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (second p)
   label ^{:line 131 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (nth p 2)
   period-orders ^{:line 132 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (ord/orders-in-period orders start end)
   cnt ^{:line 133 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (count period-orders)]
  ^{:line 134 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (->PeriodMetric label "order-count" cnt))) periods))

^{:line 138 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (defn avg-order-value-by-period [orders periods]
  ^{:line 139 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (mapv ^{:line 139 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (fn [p] ^{:line 140 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (let [start ^{:line 140 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (first p)
   end ^{:line 141 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (second p)
   label ^{:line 142 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (nth p 2)
   period-orders ^{:line 143 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (ord/orders-in-period orders start end)
   avg-val ^{:line 144 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (ord/avg-order-value period-orders)]
  ^{:line 145 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (->PeriodMetric label "avg-order-value" avg-val))) periods))

^{:line 150 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (defn discount-by-period [orders periods]
  ^{:line 151 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (mapv ^{:line 151 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (fn [p] ^{:line 152 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (let [start ^{:line 152 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (first p)
   end ^{:line 153 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (second p)
   label ^{:line 154 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (nth p 2)
   period-orders ^{:line 155 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (ord/orders-in-period orders start end)
   disc ^{:line 156 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (ord/total-discounts-given period-orders)]
  ^{:line 157 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (->PeriodMetric label "discounts" disc))) periods))

^{:line 162 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (defn tax-by-period [orders periods]
  ^{:line 163 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (mapv ^{:line 163 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (fn [p] ^{:line 164 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (let [start ^{:line 164 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (first p)
   end ^{:line 165 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (second p)
   label ^{:line 166 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (nth p 2)
   period-orders ^{:line 167 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (ord/orders-in-period orders start end)
   tx ^{:line 168 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (ord/total-tax-collected period-orders)]
  ^{:line 169 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (->PeriodMetric label "tax" tx))) periods))

^{:line 174 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (defn units-by-period [orders periods]
  ^{:line 175 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (mapv ^{:line 175 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (fn [p] ^{:line 176 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (let [start ^{:line 176 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (first p)
   end ^{:line 177 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (second p)
   label ^{:line 178 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (nth p 2)
   period-orders ^{:line 179 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (ord/orders-in-period orders start end)
   units ^{:line 180 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (ord/total-units-ordered period-orders)]
  ^{:line 181 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (->PeriodMetric label "units-ordered" units))) periods))

^{:line 190 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (defn inventory-value-metric [levels products label]
  ^{:line 192 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (let [val ^{:line 192 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (inv/total-inventory-value levels products)]
  ^{:line 193 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (->PeriodMetric label "inventory-value" val)))

^{:line 197 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (defn low-stock-count-metric [levels label]
  ^{:line 199 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (let [cnt ^{:line 199 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (count ^{:line 199 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (inv/low-stock-items levels))]
  ^{:line 200 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (->PeriodMetric label "low-stock-count" cnt)))

^{:line 204 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (defn out-of-stock-count-metric [levels label]
  ^{:line 206 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (let [cnt ^{:line 206 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (count ^{:line 206 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (inv/out-of-stock-items levels))]
  ^{:line 207 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (->PeriodMetric label "out-of-stock-count" cnt)))

^{:line 211 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (defn retail-value-metric [levels products label]
  ^{:line 213 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (let [val ^{:line 213 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (inv/stock-retail-value levels products)]
  ^{:line 214 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (->PeriodMetric label "retail-value" val)))

^{:line 219 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (defn inventory-snapshot [levels products label]
  ^{:line 221 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} [^{:line 221 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (inventory-value-metric levels products label) ^{:line 222 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (retail-value-metric levels products label) ^{:line 223 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (low-stock-count-metric levels label) ^{:line 224 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (out-of-stock-count-metric levels label)])

^{:line 232 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (defn collection-by-period [payments invoices periods]
  ^{:line 234 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (mapv ^{:line 234 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (fn [p] ^{:line 235 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (let [start ^{:line 235 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (first p)
   end ^{:line 236 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (second p)
   label ^{:line 237 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (nth p 2)
   period-payments ^{:line 238 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (filterv ^{:line 239 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (fn [pay] ^{:line 240 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (and ^{:line 240 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (= ^{:line 240 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (payment-status pay) "completed") ^{:line 241 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (>= ^{:line 241 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (payment-processed-at pay) start) ^{:line 242 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (<= ^{:line 242 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (payment-processed-at pay) end))) payments)
   total ^{:line 244 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (reduce ^{:line 244 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (fn [acc pay] ^{:line 244 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (+ acc ^{:line 244 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (payment-amount pay))) 0 period-payments)]
  ^{:line 246 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (->PeriodMetric label "collections" total))) periods))

^{:line 251 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (defn outstanding-by-period [invoices payments periods]
  ^{:line 253 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (mapv ^{:line 253 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (fn [p] ^{:line 254 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (let [label ^{:line 254 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (nth p 2)
   outstanding ^{:line 255 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (total-outstanding invoices payments)]
  ^{:line 256 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (->PeriodMetric label "outstanding" outstanding))) periods))

^{:line 261 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (defn invoiced-by-period [invoices periods]
  ^{:line 262 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (mapv ^{:line 262 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (fn [p] ^{:line 263 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (let [start ^{:line 263 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (first p)
   end ^{:line 264 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (second p)
   label ^{:line 265 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (nth p 2)
   period-invoices ^{:line 266 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (filterv ^{:line 267 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (fn [inv] ^{:line 268 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (and ^{:line 268 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (>= ^{:line 268 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (invoice-issued-at inv) start) ^{:line 269 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (<= ^{:line 269 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (invoice-issued-at inv) end))) invoices)
   total ^{:line 271 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (reduce ^{:line 271 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (fn [acc inv] ^{:line 271 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (+ acc ^{:line 271 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (invoice-total inv))) 0 period-invoices)]
  ^{:line 273 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (->PeriodMetric label "invoiced" total))) periods))

^{:line 278 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (defn overdue-count-by-period [invoices periods]
  ^{:line 279 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (mapv ^{:line 279 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (fn [p] ^{:line 280 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (let [end ^{:line 280 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (second p)
   label ^{:line 281 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (nth p 2)
   overdue ^{:line 282 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (overdue-invoices invoices end)
   cnt ^{:line 283 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (count overdue)]
  ^{:line 284 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (->PeriodMetric label "overdue-count" cnt))) periods))

^{:line 289 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (defn collection-rate-by-period [invoices payments periods]
  ^{:line 291 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (mapv ^{:line 291 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (fn [p] ^{:line 292 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (let [label ^{:line 292 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (nth p 2)
   rate ^{:line 293 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (collection-rate-pct invoices payments)]
  ^{:line 294 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (->PeriodMetric label "collection-rate" rate))) periods))

^{:line 303 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (defn shipping-cost-by-period [shipments periods]
  ^{:line 304 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (mapv ^{:line 304 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (fn [p] ^{:line 305 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (let [start ^{:line 305 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (first p)
   end ^{:line 306 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (second p)
   label ^{:line 307 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (nth p 2)
   period-delivered ^{:line 308 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (filterv ^{:line 309 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (fn [s] ^{:line 310 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (and ^{:line 310 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (= ^{:line 310 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (ship/shipment-status s) "delivered") ^{:line 311 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (>= ^{:line 311 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (ship/shipment-created-at s) start) ^{:line 312 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (<= ^{:line 312 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (ship/shipment-created-at s) end))) shipments)
   total ^{:line 314 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (reduce ^{:line 314 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (fn [acc s] ^{:line 315 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (+ acc ^{:line 315 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (ship/shipment-shipping-cost s))) 0 period-delivered)]
  ^{:line 317 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (->PeriodMetric label "shipping-cost" total))) periods))

^{:line 322 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (defn delivery-count-by-period [shipments periods]
  ^{:line 323 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (mapv ^{:line 323 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (fn [p] ^{:line 324 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (let [start ^{:line 324 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (first p)
   end ^{:line 325 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (second p)
   label ^{:line 326 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (nth p 2)
   period-delivered ^{:line 327 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (filterv ^{:line 328 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (fn [s] ^{:line 329 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (and ^{:line 329 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (= ^{:line 329 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (ship/shipment-status s) "delivered") ^{:line 330 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (>= ^{:line 330 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (ship/shipment-created-at s) start) ^{:line 331 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (<= ^{:line 331 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (ship/shipment-created-at s) end))) shipments)
   cnt ^{:line 333 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (count period-delivered)]
  ^{:line 334 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (->PeriodMetric label "deliveries" cnt))) periods))

^{:line 339 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (defn shipment-count-by-period [shipments periods]
  ^{:line 340 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (mapv ^{:line 340 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (fn [p] ^{:line 341 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (let [start ^{:line 341 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (first p)
   end ^{:line 342 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (second p)
   label ^{:line 343 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (nth p 2)
   period-ships ^{:line 344 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (filterv ^{:line 345 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (fn [s] ^{:line 346 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (and ^{:line 346 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (not= ^{:line 346 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (ship/shipment-status s) "cancelled") ^{:line 347 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (>= ^{:line 347 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (ship/shipment-created-at s) start) ^{:line 348 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (<= ^{:line 348 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (ship/shipment-created-at s) end))) shipments)
   cnt ^{:line 350 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (count period-ships)]
  ^{:line 351 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (->PeriodMetric label "shipment-count" cnt))) periods))

^{:line 356 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (defn avg-shipping-cost-by-period [shipments periods]
  ^{:line 357 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (mapv ^{:line 357 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (fn [p] ^{:line 358 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (let [start ^{:line 358 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (first p)
   end ^{:line 359 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (second p)
   label ^{:line 360 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (nth p 2)
   period-ships ^{:line 361 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (filterv ^{:line 362 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (fn [s] ^{:line 363 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (and ^{:line 363 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (not= ^{:line 363 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (ship/shipment-status s) "cancelled") ^{:line 364 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (>= ^{:line 364 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (ship/shipment-created-at s) start) ^{:line 365 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (<= ^{:line 365 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (ship/shipment-created-at s) end))) shipments)
   cnt ^{:line 367 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (count period-ships)
   total ^{:line 368 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (reduce ^{:line 368 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (fn [acc s] ^{:line 369 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (+ acc ^{:line 369 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (ship/shipment-shipping-cost s))) 0 period-ships)
   avg-cost ^{:line 371 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (if ^{:line 371 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (= cnt 0) 0 ^{:line 371 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (quot total cnt))]
  ^{:line 372 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (->PeriodMetric label "avg-shipping-cost" avg-cost))) periods))

^{:line 377 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (defn total-weight-by-period [shipments periods]
  ^{:line 378 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (mapv ^{:line 378 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (fn [p] ^{:line 379 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (let [start ^{:line 379 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (first p)
   end ^{:line 380 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (second p)
   label ^{:line 381 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (nth p 2)
   period-delivered ^{:line 382 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (filterv ^{:line 383 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (fn [s] ^{:line 384 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (and ^{:line 384 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (= ^{:line 384 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (ship/shipment-status s) "delivered") ^{:line 385 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (>= ^{:line 385 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (ship/shipment-created-at s) start) ^{:line 386 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (<= ^{:line 386 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (ship/shipment-created-at s) end))) shipments)
   total-wt ^{:line 388 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (reduce ^{:line 388 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (fn [acc s] ^{:line 389 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (+ acc ^{:line 389 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (ship/shipment-weight-kg s))) 0 period-delivered)]
  ^{:line 391 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (->PeriodMetric label "total-weight" total-wt))) periods))

^{:line 401 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (defn calculate-trend [metrics metric-name]
  ^{:line 402 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (let [sorted ^{:line 402 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (sort-by periodmetric-period ^{:line 403 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (filterv ^{:line 403 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (fn [m] ^{:line 403 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (= ^{:line 403 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (periodmetric-metric-name m) metric-name)) metrics))
   vals ^{:line 405 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (mapv periodmetric-value sorted)]
  ^{:line 406 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (if ^{:line 406 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (< ^{:line 406 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (count vals) 2) ^{:line 407 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (->TrendResult metric-name "flat" 0) ^{:line 408 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (let [first-val ^{:line 408 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (periodmetric-value ^{:line 408 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (first sorted))
   last-val ^{:line 409 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (last vals)]
  ^{:line 410 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (cond
  ^{:line 411 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (= first-val last-val) ^{:line 412 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (->TrendResult metric-name "flat" 0)
  ^{:line 413 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (> last-val first-val) ^{:line 414 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (let [change ^{:line 414 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (if ^{:line 414 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (= first-val 0) 0 ^{:line 415 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (quot ^{:line 415 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (* ^{:line 415 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (- last-val first-val) 100) first-val))]
  ^{:line 416 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (->TrendResult metric-name "up" change))
  true ^{:line 418 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (let [change ^{:line 418 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (if ^{:line 418 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (= first-val 0) 0 ^{:line 419 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (quot ^{:line 419 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (* ^{:line 419 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (- first-val last-val) 100) first-val))]
  ^{:line 420 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (->TrendResult metric-name "down" change)))))))

^{:line 424 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (defn compare-periods [metrics metric-name period1 period2]
  ^{:line 426 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (let [matching ^{:line 426 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (filterv ^{:line 426 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (fn [m] ^{:line 426 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (= ^{:line 426 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (periodmetric-metric-name m) metric-name)) metrics)
   m1 ^{:line 428 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (first ^{:line 428 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (filterv ^{:line 428 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (fn [m] ^{:line 428 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (= ^{:line 428 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (periodmetric-period m) period1)) matching))
   m2 ^{:line 430 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (first ^{:line 430 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (filterv ^{:line 430 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (fn [m] ^{:line 430 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (= ^{:line 430 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (periodmetric-period m) period2)) matching))
   v1 ^{:line 432 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (if ^{:line 432 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (nil? m1) 0 ^{:line 432 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (periodmetric-value m1))
   v2 ^{:line 433 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (if ^{:line 433 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (nil? m2) 0 ^{:line 433 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (periodmetric-value m2))]
  ^{:line 434 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (cond
  ^{:line 435 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (= v1 v2) ^{:line 436 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (->TrendResult metric-name "flat" 0)
  ^{:line 437 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (> v2 v1) ^{:line 438 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (let [change ^{:line 438 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (if ^{:line 438 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (= v1 0) 0 ^{:line 438 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (quot ^{:line 438 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (* ^{:line 438 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (- v2 v1) 100) v1))]
  ^{:line 439 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (->TrendResult metric-name "up" change))
  true ^{:line 441 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (let [change ^{:line 441 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (if ^{:line 441 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (= v1 0) 0 ^{:line 441 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (quot ^{:line 441 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (* ^{:line 441 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (- v1 v2) 100) v1))]
  ^{:line 442 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (->TrendResult metric-name "down" change)))))

^{:line 445 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (defn trend-direction [tr]
  ^{:line 446 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (trendresult-direction tr))

^{:line 449 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (defn trend-is-positive? [tr]
  ^{:line 450 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (= ^{:line 450 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (trendresult-direction tr) "up"))

^{:line 453 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (defn trend-is-negative? [tr]
  ^{:line 454 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (= ^{:line 454 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (trendresult-direction tr) "down"))

^{:line 457 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (defn trend-magnitude [tr]
  ^{:line 458 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (trendresult-change-pct tr))

^{:line 461 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (defn trend-summary [tr]
  ^{:line 462 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (let [name ^{:line 462 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (trendresult-metric-name tr)
   dir ^{:line 463 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (trendresult-direction tr)
   pct ^{:line 464 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (trendresult-change-pct tr)]
  ^{:line 465 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (cond
  ^{:line 466 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (= dir "flat") ^{:line 467 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (str name ": flat (no change)")
  ^{:line 468 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (= dir "up") ^{:line 469 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (str name ": up " pct "%")
  true ^{:line 471 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (str name ": down " pct "%"))))

^{:line 475 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (defn multi-trend [metrics metric-names]
  ^{:line 476 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (mapv ^{:line 476 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (fn [name] ^{:line 476 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (calculate-trend metrics name)) metric-names))

^{:line 484 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (defn bucket-orders-by-value [orders thresholds]
  ^{:line 485 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (mapv ^{:line 485 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (fn [t] ^{:line 486 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (let [label ^{:line 486 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (first t)
   lo ^{:line 487 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (second t)
   hi ^{:line 488 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (nth t 2)
   matching ^{:line 489 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (filterv ^{:line 489 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (fn [o] ^{:line 490 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (and ^{:line 490 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (>= ^{:line 490 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (ord/order-total o) lo) ^{:line 491 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (<= ^{:line 491 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (ord/order-total o) hi))) orders)
   cnt ^{:line 493 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (count matching)
   total ^{:line 494 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (reduce ^{:line 494 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (fn [acc o] ^{:line 494 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (+ acc ^{:line 494 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (ord/order-total o))) 0 matching)]
  ^{:line 496 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (->Bucket label cnt total))) thresholds))

^{:line 502 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (defn bucket-customers-by-spend [customers orders thresholds]
  ^{:line 504 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (mapv ^{:line 504 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (fn [t] ^{:line 505 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (let [label ^{:line 505 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (first t)
   lo ^{:line 506 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (second t)
   hi ^{:line 507 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (nth t 2)
   results ^{:line 508 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (reduce ^{:line 509 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (fn [acc cid] ^{:line 510 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (let [spend ^{:line 510 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (ord/customer-total-spend orders cid)]
  ^{:line 511 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (if ^{:line 511 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (and ^{:line 511 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (>= spend lo) ^{:line 511 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (<= spend hi)) ^{:line 512 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} {:count ^{:line 512 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (+ ^{:line 512 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (:count acc) 1) :total ^{:line 512 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (+ ^{:line 512 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (:total acc) spend)} acc))) ^{:line 515 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} {:count 0 :total 0} customers)]
  ^{:line 517 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (->Bucket label ^{:line 517 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (:count results) ^{:line 517 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (:total results)))) thresholds))

^{:line 521 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (defn sum-bucket-totals [buckets]
  ^{:line 522 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (reduce ^{:line 522 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (fn [acc b] ^{:line 522 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (+ acc ^{:line 522 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (bucket-total b))) 0 buckets))

^{:line 525 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (defn sum-bucket-counts [buckets]
  ^{:line 526 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (reduce ^{:line 526 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (fn [acc b] ^{:line 526 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (+ acc ^{:line 526 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (bucket-count b))) 0 buckets))

^{:line 529 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (defn largest-bucket [buckets]
  ^{:line 530 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (if ^{:line 530 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (empty? buckets) nil ^{:line 532 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (reduce ^{:line 532 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (fn [best b] ^{:line 533 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (if ^{:line 533 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (> ^{:line 533 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (bucket-total b) ^{:line 533 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (bucket-total best)) b best)) ^{:line 534 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (first buckets) ^{:line 535 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (rest buckets))))

^{:line 538 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (defn most-populated-bucket [buckets]
  ^{:line 539 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (if ^{:line 539 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (empty? buckets) nil ^{:line 541 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (reduce ^{:line 541 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (fn [best b] ^{:line 542 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (if ^{:line 542 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (> ^{:line 542 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (bucket-count b) ^{:line 542 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (bucket-count best)) b best)) ^{:line 543 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (first buckets) ^{:line 544 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (rest buckets))))

^{:line 547 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (defn bucket-summary [b]
  ^{:line 548 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (str ^{:line 548 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (bucket-label b) ": " ^{:line 549 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (bucket-count b) " items" ", total " ^{:line 550 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (cat/format-price ^{:line 550 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (bucket-total b))))

^{:line 554 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (defn bucket-distribution [buckets]
  ^{:line 555 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (let [grand ^{:line 555 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (reduce ^{:line 555 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (fn [acc b] ^{:line 555 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (+ acc ^{:line 555 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (bucket-total b))) 0 buckets)]
  ^{:line 556 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (mapv ^{:line 556 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (fn [b] ^{:line 557 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (let [pct ^{:line 557 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (if ^{:line 557 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (= grand 0) 0 ^{:line 558 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (quot ^{:line 558 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (* ^{:line 558 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (bucket-total b) 100) grand))]
  ^{:line 559 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} {:label ^{:line 559 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (bucket-label b) :count ^{:line 559 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (bucket-count b) :total ^{:line 559 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (bucket-total b) :pct pct})) buckets)))

^{:line 572 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (defn gross-margin-metric [orders label]
  ^{:line 573 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (let [rev ^{:line 573 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (ord/total-revenue orders)
   disc ^{:line 576 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (ord/total-discounts-given orders)
   margin ^{:line 577 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (- rev disc)]
  ^{:line 578 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (->PeriodMetric label "gross-margin" margin)))

^{:line 582 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (defn shipping-to-revenue-pct [orders shipments]
  ^{:line 583 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (let [rev ^{:line 583 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (ord/total-revenue orders)
   ship-cost ^{:line 584 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (ship/total-shipping-revenue shipments)]
  ^{:line 585 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (if ^{:line 585 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (= rev 0) 0 ^{:line 586 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (quot ^{:line 586 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (* ship-cost 100) rev))))

^{:line 591 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (defn inventory-turnover-ratio [orders levels products]
  ^{:line 593 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (let [rev ^{:line 593 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (ord/total-revenue orders)
   inv-val ^{:line 594 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (inv/total-inventory-value levels products)]
  ^{:line 595 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (if ^{:line 595 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (= inv-val 0) 0 ^{:line 596 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (quot ^{:line 596 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (* rev 100) inv-val))))

^{:line 604 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (defn revenue-per-order-line [orders]
  ^{:line 605 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (let [rev ^{:line 605 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (ord/total-revenue orders)
   lines ^{:line 606 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (ord/total-line-count orders)]
  ^{:line 607 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (if ^{:line 607 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (= lines 0) 0 ^{:line 608 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (quot rev lines))))

^{:line 612 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (defn order-size-distribution [orders small-max large-min]
  ^{:line 614 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (let [small-cnt ^{:line 614 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (count ^{:line 614 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (filterv ^{:line 614 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (fn [o] ^{:line 614 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (<= ^{:line 614 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (ord/order-total o) small-max)) orders))
   large-cnt ^{:line 616 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (count ^{:line 616 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (filterv ^{:line 616 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (fn [o] ^{:line 616 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (>= ^{:line 616 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (ord/order-total o) large-min)) orders))
   medium-cnt ^{:line 618 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (count ^{:line 618 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (filterv ^{:line 618 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (fn [o] ^{:line 619 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (and ^{:line 619 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (> ^{:line 619 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (ord/order-total o) small-max) ^{:line 620 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (< ^{:line 620 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (ord/order-total o) large-min))) orders))]
  ^{:line 622 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} {:small small-cnt :medium medium-cnt :large large-cnt}))

^{:line 634 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (defn kpi-dashboard [orders invoices payments shipments levels products]
  ^{:line 637 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (let [total-rev ^{:line 637 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (ord/total-revenue orders)
   total-collected ^{:line 638 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (total-revenue-collected payments)
   total-out ^{:line 639 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (total-outstanding invoices payments)
   total-ship ^{:line 640 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (ship/total-shipping-revenue shipments)
   inv-val ^{:line 641 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (inv/total-inventory-value levels products)
   order-cnt ^{:line 642 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (count orders)]
  ^{:line 643 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} {:total-revenue total-rev :total-collected total-collected :total-outstanding total-out :total-shipping total-ship :inventory-value inv-val :order-count order-cnt}))

^{:line 652 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (defn extended-kpi-dashboard [orders invoices payments shipments levels products]
  ^{:line 655 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (let [base ^{:line 655 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (kpi-dashboard orders invoices payments shipments levels products)
   avg-order ^{:line 657 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (ord/avg-order-value orders)
   total-lines ^{:line 658 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (ord/total-line-count orders)
   total-units ^{:line 659 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (ord/total-units-ordered orders)
   total-disc ^{:line 660 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (ord/total-discounts-given orders)
   total-tax ^{:line 661 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (ord/total-tax-collected orders)
   pending-cnt ^{:line 662 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (count ^{:line 662 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (ord/pending-orders orders))
   active-cnt ^{:line 663 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (count ^{:line 663 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (ord/active-orders orders))
   low-stock-cnt ^{:line 664 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (count ^{:line 664 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (inv/low-stock-items levels))
   oos-cnt ^{:line 665 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (count ^{:line 665 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (inv/out-of-stock-items levels))
   ship-rev ^{:line 666 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (ship/total-shipping-revenue shipments)
   avg-ship ^{:line 667 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (ship/avg-shipping-cost shipments)
   avg-delivery ^{:line 668 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (ship/avg-delivery-time-days shipments)
   coll-rate ^{:line 669 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (collection-rate-pct invoices payments)
   overdue-cnt ^{:line 670 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (count ^{:line 670 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (overdue-invoices invoices 0))
   net-rev ^{:line 671 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (net-revenue payments)]
  ^{:line 672 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} {:total-revenue ^{:line 672 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (:total-revenue base) :total-collected ^{:line 672 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (:total-collected base) :total-outstanding ^{:line 672 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (:total-outstanding base) :total-shipping ^{:line 672 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (:total-shipping base) :inventory-value ^{:line 672 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (:inventory-value base) :order-count ^{:line 672 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (:order-count base) :avg-order-value avg-order :total-line-items total-lines :total-units-ordered total-units :total-discounts total-disc :total-tax total-tax :pending-orders pending-cnt :active-orders active-cnt :low-stock-count low-stock-cnt :out-of-stock-count oos-cnt :avg-shipping-cost avg-ship :avg-delivery-days avg-delivery :collection-rate coll-rate :overdue-invoices overdue-cnt :net-revenue net-rev}))

^{:line 700 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (defn period-over-period [metrics metric-name period1 period2]
  ^{:line 702 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (let [matching ^{:line 702 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (filterv ^{:line 702 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (fn [m] ^{:line 702 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (= ^{:line 702 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (periodmetric-metric-name m) metric-name)) metrics)
   m1 ^{:line 704 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (first ^{:line 704 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (filterv ^{:line 704 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (fn [m] ^{:line 704 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (= ^{:line 704 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (periodmetric-period m) period1)) matching))
   m2 ^{:line 706 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (first ^{:line 706 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (filterv ^{:line 706 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (fn [m] ^{:line 706 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (= ^{:line 706 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (periodmetric-period m) period2)) matching))
   v1 ^{:line 708 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (if ^{:line 708 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (nil? m1) 0 ^{:line 708 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (periodmetric-value m1))
   v2 ^{:line 709 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (if ^{:line 709 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (nil? m2) 0 ^{:line 709 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (periodmetric-value m2))
   abs-change ^{:line 710 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (- v2 v1)
   pct-change ^{:line 711 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (if ^{:line 711 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (= v1 0) 0 ^{:line 711 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (quot ^{:line 711 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (* abs-change 100) v1))]
  ^{:line 712 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} {:metric metric-name :period1 period1 :period2 period2 :value1 v1 :value2 v2 :change abs-change :change-pct pct-change}))

^{:line 723 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (defn generate-all-metrics [orders periods]
  ^{:line 724 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (let [rev ^{:line 724 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (revenue-by-period orders periods)
   cnt ^{:line 725 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (order-count-by-period orders periods)
   avg-val ^{:line 726 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (avg-order-value-by-period orders periods)
   disc ^{:line 727 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (discount-by-period orders periods)
   tx ^{:line 728 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (tax-by-period orders periods)
   units ^{:line 729 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (units-by-period orders periods)]
  ^{:line 730 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (into ^{:line 730 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} [] ^{:line 730 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (concat rev cnt avg-val disc tx units))))

^{:line 737 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (defn format-metric [m]
  ^{:line 738 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (str "[" ^{:line 738 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (periodmetric-period m) "] " ^{:line 739 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (periodmetric-metric-name m) " = " ^{:line 740 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (periodmetric-value m)))

^{:line 743 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (defn format-trend [tr]
  ^{:line 744 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (str ^{:line 744 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (trendresult-metric-name tr) ": " ^{:line 745 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (trendresult-direction tr) " " ^{:line 746 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (trendresult-change-pct tr) "%"))

^{:line 749 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (defn format-bucket [b]
  ^{:line 750 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (str ^{:line 750 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (bucket-label b) ": " ^{:line 751 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (bucket-count b) " items, " ^{:line 752 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (cat/format-price ^{:line 752 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (bucket-total b))))

^{:line 759 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (defn valid-period-metric? [m]
  ^{:line 760 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (and ^{:line 760 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (not= ^{:line 760 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (periodmetric-period m) "") ^{:line 761 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (not= ^{:line 761 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (periodmetric-metric-name m) "")))

^{:line 764 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (defn valid-trend-result? [tr]
  ^{:line 765 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (and ^{:line 765 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (not= ^{:line 765 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (trendresult-metric-name tr) "") ^{:line 766 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (or ^{:line 766 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (= ^{:line 766 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (trendresult-direction tr) "up") ^{:line 767 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (= ^{:line 767 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (trendresult-direction tr) "down") ^{:line 768 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (= ^{:line 768 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (trendresult-direction tr) "flat")) ^{:line 769 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (>= ^{:line 769 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (trendresult-change-pct tr) 0)))

^{:line 772 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (defn valid-bucket? [b]
  ^{:line 773 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (and ^{:line 773 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (not= ^{:line 773 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (bucket-label b) "") ^{:line 774 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (>= ^{:line 774 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (bucket-count b) 0) ^{:line 775 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (>= ^{:line 775 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (bucket-total b) 0)))

^{:line 782 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (defn sort-metrics-by-value [metrics]
  ^{:line 783 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (sort-by periodmetric-value metrics))

^{:line 786 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (defn sort-metrics-by-period [metrics]
  ^{:line 787 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (sort-by periodmetric-period metrics))

^{:line 790 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (defn sort-buckets-by-total [buckets]
  ^{:line 791 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (sort-by bucket-total buckets))

^{:line 794 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (defn sort-buckets-by-count [buckets]
  ^{:line 795 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (sort-by bucket-count buckets))

^{:line 798 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (defn top-metrics [metrics metric-name n]
  ^{:line 800 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (let [matching ^{:line 800 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (filterv ^{:line 800 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (fn [m] ^{:line 800 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (= ^{:line 800 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (periodmetric-metric-name m) metric-name)) metrics)
   sorted ^{:line 802 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (reverse ^{:line 802 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (sort-by periodmetric-value matching))]
  ^{:line 803 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (vec ^{:line 803 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (take n sorted))))

^{:line 806 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (defn bottom-metrics [metrics metric-name n]
  ^{:line 808 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (let [matching ^{:line 808 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (filterv ^{:line 808 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (fn [m] ^{:line 808 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (= ^{:line 808 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (periodmetric-metric-name m) metric-name)) metrics)
   sorted ^{:line 810 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (sort-by periodmetric-value matching)]
  ^{:line 811 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (vec ^{:line 811 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (take n sorted))))

^{:line 819 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (defn analytics-summary [orders invoices payments shipments levels products periods]
  ^{:line 822 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (let [rev-metrics ^{:line 822 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (revenue-by-period orders periods)
   cnt-metrics ^{:line 823 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (order-count-by-period orders periods)
   coll-metrics ^{:line 824 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (collection-by-period payments invoices periods)
   ship-metrics ^{:line 825 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (shipping-cost-by-period shipments periods)
   del-metrics ^{:line 826 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (delivery-count-by-period shipments periods)
   rev-trend ^{:line 827 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (calculate-trend rev-metrics "revenue")
   cnt-trend ^{:line 828 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (calculate-trend cnt-metrics "order-count")
   coll-trend ^{:line 829 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (calculate-trend coll-metrics "collections")
   ship-trend ^{:line 830 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (calculate-trend ship-metrics "shipping-cost")
   kpi ^{:line 831 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (kpi-dashboard orders invoices payments shipments levels products)]
  ^{:line 833 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} {:kpi kpi :revenue-trend ^{:line 833 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (trendresult-direction rev-trend) :revenue-change-pct ^{:line 833 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (trendresult-change-pct rev-trend) :order-count-trend ^{:line 833 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (trendresult-direction cnt-trend) :order-count-change-pct ^{:line 833 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (trendresult-change-pct cnt-trend) :collections-trend ^{:line 833 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (trendresult-direction coll-trend) :collections-change-pct ^{:line 833 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (trendresult-change-pct coll-trend) :shipping-trend ^{:line 833 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (trendresult-direction ship-trend) :shipping-change-pct ^{:line 833 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/analytics.rkt"} (trendresult-change-pct ship-trend) :revenue-metrics rev-metrics :order-count-metrics cnt-metrics :collection-metrics coll-metrics :shipping-cost-metrics ship-metrics :delivery-metrics del-metrics}))
