(ns procurement
  (:require [catalog :refer :all :as cat]
            [inventory :refer :all :as inv]))

^{:line 12 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (defrecord PurchaseOrder [id supplier-id status created-at expected-at total])

(defn purchaseorder-id [r] (:id r))

(defn purchaseorder-supplier-id [r] (:supplier-id r))

(defn purchaseorder-status [r] (:status r))

(defn purchaseorder-created-at [r] (:created-at r))

(defn purchaseorder-expected-at [r] (:expected-at r))

(defn purchaseorder-total [r] (:total r))

^{:line 16 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (defrecord POLine [po-id product-id quantity unit-cost])

(defn poline-po-id [r] (:po-id r))

(defn poline-product-id [r] (:product-id r))

(defn poline-quantity [r] (:quantity r))

(defn poline-unit-cost [r] (:unit-cost r))

^{:line 19 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (defrecord GoodsReceipt [id po-id warehouse-id received-at line-count])

(defn goodsreceipt-id [r] (:id r))

(defn goodsreceipt-po-id [r] (:po-id r))

(defn goodsreceipt-warehouse-id [r] (:warehouse-id r))

(defn goodsreceipt-received-at [r] (:received-at r))

(defn goodsreceipt-line-count [r] (:line-count r))

^{:line 27 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (defn poline-total [line]
  ^{:line 28 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (* ^{:line 28 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (poline-quantity line) ^{:line 28 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (poline-unit-cost line)))

^{:line 31 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (defn po-total-from-lines [lines]
  ^{:line 32 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (reduce ^{:line 32 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (fn [acc line] ^{:line 32 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (+ acc ^{:line 32 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (poline-total line))) 0 lines))

^{:line 35 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (defn po-line-count [lines po-id]
  ^{:line 36 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (count ^{:line 36 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (filterv ^{:line 36 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (fn [line] ^{:line 36 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (= ^{:line 36 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (poline-po-id line) po-id)) lines)))

^{:line 39 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (defn lines-for-po [lines po-id]
  ^{:line 40 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (filterv ^{:line 40 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (fn [line] ^{:line 40 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (= ^{:line 40 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (poline-po-id line) po-id)) lines))

^{:line 43 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (defn lines-for-product [lines product-id]
  ^{:line 44 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (filterv ^{:line 44 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (fn [line] ^{:line 44 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (= ^{:line 44 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (poline-product-id line) product-id)) lines))

^{:line 47 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (defn total-quantity-for-product [lines product-id]
  ^{:line 48 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (reduce ^{:line 48 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (fn [acc line] ^{:line 48 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (+ acc ^{:line 48 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (poline-quantity line))) 0 ^{:line 50 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (lines-for-product lines product-id)))

^{:line 53 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (defn total-spend-for-product [lines product-id]
  ^{:line 54 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (reduce ^{:line 54 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (fn [acc line] ^{:line 54 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (+ acc ^{:line 54 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (poline-total line))) 0 ^{:line 56 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (lines-for-product lines product-id)))

^{:line 59 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (defn avg-unit-cost-for-product [lines product-id]
  ^{:line 60 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (let [prod-lines ^{:line 60 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (lines-for-product lines product-id)
   cnt ^{:line 61 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (count prod-lines)]
  ^{:line 62 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (if ^{:line 62 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (= cnt 0) 0 ^{:line 63 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (quot ^{:line 63 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (total-spend-for-product lines product-id) ^{:line 64 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (total-quantity-for-product lines product-id)))))

^{:line 67 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (defn unique-products-in-lines [lines]
  ^{:line 68 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (distinct ^{:line 68 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (mapv poline-product-id lines)))

^{:line 75 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (defn create-purchase-order [id supplier-id lines created-at expected-at]
  ^{:line 78 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (let [total ^{:line 78 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (po-total-from-lines lines)]
  ^{:line 79 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (->PurchaseOrder id supplier-id "pending" created-at expected-at total)))

^{:line 86 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (defn find-po-by-id [pos id]
  ^{:line 87 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (first ^{:line 87 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (filterv ^{:line 87 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (fn [po] ^{:line 87 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (= ^{:line 87 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (purchaseorder-id po) id)) pos)))

^{:line 90 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (defn pos-for-supplier [pos supplier-id]
  ^{:line 91 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (filterv ^{:line 91 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (fn [po] ^{:line 91 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (= ^{:line 91 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (purchaseorder-supplier-id po) supplier-id)) pos))

^{:line 94 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (defn pos-by-status [pos status]
  ^{:line 95 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (filterv ^{:line 95 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (fn [po] ^{:line 95 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (= ^{:line 95 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (purchaseorder-status po) status)) pos))

^{:line 98 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (defn pending-pos [pos]
  ^{:line 99 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (filterv ^{:line 99 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (fn [po] ^{:line 99 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (= ^{:line 99 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (purchaseorder-status po) "pending")) pos))

^{:line 102 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (defn approved-pos [pos]
  ^{:line 103 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (filterv ^{:line 103 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (fn [po] ^{:line 103 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (= ^{:line 103 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (purchaseorder-status po) "approved")) pos))

^{:line 106 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (defn completed-pos [pos]
  ^{:line 107 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (filterv ^{:line 107 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (fn [po] ^{:line 107 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (= ^{:line 107 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (purchaseorder-status po) "completed")) pos))

^{:line 110 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (defn cancelled-pos [pos]
  ^{:line 111 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (filterv ^{:line 111 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (fn [po] ^{:line 111 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (= ^{:line 111 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (purchaseorder-status po) "cancelled")) pos))

^{:line 114 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (defn pos-in-period [pos start end]
  ^{:line 115 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (filterv ^{:line 115 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (fn [po] ^{:line 115 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (and ^{:line 115 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (>= ^{:line 115 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (purchaseorder-created-at po) start) ^{:line 116 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (<= ^{:line 116 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (purchaseorder-created-at po) end))) pos))

^{:line 120 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (defn sort-pos-by-total [pos]
  ^{:line 121 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (reverse ^{:line 121 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (sort-by purchaseorder-total pos)))

^{:line 124 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (defn sort-pos-by-date [pos]
  ^{:line 125 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (sort-by purchaseorder-created-at pos))

^{:line 132 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (defn approve-po [po]
  ^{:line 133 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (if ^{:line 133 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (= ^{:line 133 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (purchaseorder-status po) "pending") ^{:line 134 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (->PurchaseOrder ^{:line 134 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (purchaseorder-id po) ^{:line 135 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (purchaseorder-supplier-id po) "approved" ^{:line 137 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (purchaseorder-created-at po) ^{:line 138 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (purchaseorder-expected-at po) ^{:line 139 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (purchaseorder-total po)) po))

^{:line 143 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (defn complete-po [po]
  ^{:line 144 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (->PurchaseOrder ^{:line 144 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (purchaseorder-id po) ^{:line 145 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (purchaseorder-supplier-id po) "completed" ^{:line 147 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (purchaseorder-created-at po) ^{:line 148 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (purchaseorder-expected-at po) ^{:line 149 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (purchaseorder-total po)))

^{:line 152 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (defn cancel-po [po]
  ^{:line 153 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (if ^{:line 153 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (= ^{:line 153 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (purchaseorder-status po) "pending") ^{:line 154 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (->PurchaseOrder ^{:line 154 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (purchaseorder-id po) ^{:line 155 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (purchaseorder-supplier-id po) "cancelled" ^{:line 157 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (purchaseorder-created-at po) ^{:line 158 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (purchaseorder-expected-at po) ^{:line 159 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (purchaseorder-total po)) po))

^{:line 163 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (defn po-open? [po]
  ^{:line 164 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (or ^{:line 164 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (= ^{:line 164 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (purchaseorder-status po) "pending") ^{:line 165 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (= ^{:line 165 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (purchaseorder-status po) "approved")))

^{:line 168 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (defn po-closed? [po]
  ^{:line 169 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (or ^{:line 169 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (= ^{:line 169 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (purchaseorder-status po) "completed") ^{:line 170 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (= ^{:line 170 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (purchaseorder-status po) "cancelled")))

^{:line 173 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (defn po-expected-lead-days [po]
  ^{:line 174 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (let [elapsed ^{:line 174 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (- ^{:line 174 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (purchaseorder-expected-at po) ^{:line 175 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (purchaseorder-created-at po))]
  ^{:line 176 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (quot elapsed 86400)))

^{:line 184 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (defn valid-po? [po]
  ^{:line 185 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (and ^{:line 185 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (> ^{:line 185 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (purchaseorder-id po) 0) ^{:line 186 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (> ^{:line 186 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (purchaseorder-supplier-id po) 0) ^{:line 187 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (not= ^{:line 187 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (purchaseorder-status po) "") ^{:line 188 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (>= ^{:line 188 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (purchaseorder-total po) 0)))

^{:line 191 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (defn valid-poline? [line]
  ^{:line 192 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (and ^{:line 192 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (> ^{:line 192 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (poline-product-id line) 0) ^{:line 193 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (> ^{:line 193 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (poline-quantity line) 0) ^{:line 194 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (>= ^{:line 194 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (poline-unit-cost line) 0)))

^{:line 197 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (defn valid-lines [lines]
  ^{:line 198 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (filterv valid-poline? lines))

^{:line 201 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (defn all-lines-valid? [lines]
  ^{:line 202 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (every? valid-poline? lines))

^{:line 209 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (defn create-goods-receipt [id po-id warehouse-id received-at lines]
  ^{:line 212 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (let [lc ^{:line 212 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (count ^{:line 212 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (filterv ^{:line 212 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (fn [line] ^{:line 212 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (= ^{:line 212 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (poline-po-id line) po-id)) lines))]
  ^{:line 214 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (->GoodsReceipt id po-id warehouse-id received-at lc)))

^{:line 217 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (defn receipts-for-po [receipts po-id]
  ^{:line 218 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (filterv ^{:line 218 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (fn [r] ^{:line 218 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (= ^{:line 218 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (goodsreceipt-po-id r) po-id)) receipts))

^{:line 221 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (defn receipts-for-warehouse [receipts warehouse-id]
  ^{:line 222 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (filterv ^{:line 222 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (fn [r] ^{:line 222 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (= ^{:line 222 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (goodsreceipt-warehouse-id r) warehouse-id)) receipts))

^{:line 225 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (defn find-receipt-by-id [receipts id]
  ^{:line 226 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (first ^{:line 226 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (filterv ^{:line 226 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (fn [r] ^{:line 226 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (= ^{:line 226 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (goodsreceipt-id r) id)) receipts)))

^{:line 229 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (defn receipts-in-period [receipts start end]
  ^{:line 231 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (filterv ^{:line 231 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (fn [r] ^{:line 231 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (and ^{:line 231 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (>= ^{:line 231 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (goodsreceipt-received-at r) start) ^{:line 232 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (<= ^{:line 232 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (goodsreceipt-received-at r) end))) receipts))

^{:line 236 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (defn total-lines-received-for-po [receipts po-id]
  ^{:line 237 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (reduce ^{:line 237 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (fn [acc r] ^{:line 237 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (+ acc ^{:line 237 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (goodsreceipt-line-count r))) 0 ^{:line 239 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (receipts-for-po receipts po-id)))

^{:line 242 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (defn po-has-receipt? [receipts po-id]
  ^{:line 243 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (not ^{:line 243 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (empty? ^{:line 243 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (receipts-for-po receipts po-id))))

^{:line 246 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (defn warehouse-receipt-count [receipts warehouse-id]
  ^{:line 247 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (count ^{:line 247 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (receipts-for-warehouse receipts warehouse-id)))

^{:line 254 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (defn supplier-total-ordered [pos lines supplier-id]
  ^{:line 256 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (let [supplier-pos ^{:line 256 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (pos-for-supplier pos supplier-id)
   supplier-po-ids ^{:line 257 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (mapv ^{:line 257 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (fn [po] ^{:line 257 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (purchaseorder-id po)) supplier-pos)
   matching-lines ^{:line 258 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (filterv ^{:line 259 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (fn [line] ^{:line 260 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (some ^{:line 260 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (fn [pid] ^{:line 260 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (= pid ^{:line 260 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (poline-po-id line))) supplier-po-ids)) lines)]
  ^{:line 263 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (reduce ^{:line 263 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (fn [acc line] ^{:line 263 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (+ acc ^{:line 263 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (poline-quantity line))) 0 matching-lines)))

^{:line 267 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (defn supplier-order-count [pos supplier-id]
  ^{:line 268 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (count ^{:line 268 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (pos-for-supplier pos supplier-id)))

^{:line 271 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (defn supplier-avg-order-value [pos supplier-id]
  ^{:line 272 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (let [spos ^{:line 272 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (pos-for-supplier pos supplier-id)
   cnt ^{:line 273 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (count spos)]
  ^{:line 274 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (if ^{:line 274 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (= cnt 0) 0 ^{:line 275 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (let [total ^{:line 275 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (reduce ^{:line 275 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (fn [acc po] ^{:line 276 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (+ acc ^{:line 276 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (purchaseorder-total po))) 0 spos)]
  ^{:line 278 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (quot total cnt)))))

^{:line 281 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (defn supplier-completed-count [pos supplier-id]
  ^{:line 282 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (count ^{:line 282 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (filterv ^{:line 282 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (fn [po] ^{:line 282 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (= ^{:line 282 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (purchaseorder-status po) "completed")) ^{:line 283 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (pos-for-supplier pos supplier-id))))

^{:line 286 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (defn supplier-completion-rate [pos supplier-id]
  ^{:line 287 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (let [spos ^{:line 287 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (pos-for-supplier pos supplier-id)
   total ^{:line 288 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (count spos)
   completed ^{:line 289 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (count ^{:line 289 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (filterv ^{:line 289 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (fn [po] ^{:line 290 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (= ^{:line 290 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (purchaseorder-status po) "completed")) spos))]
  ^{:line 292 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (if ^{:line 292 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (= total 0) 0 ^{:line 292 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (quot ^{:line 292 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (* completed 100) total))))

^{:line 295 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (defn supplier-cancellation-rate [pos supplier-id]
  ^{:line 296 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (let [spos ^{:line 296 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (pos-for-supplier pos supplier-id)
   total ^{:line 297 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (count spos)
   cancelled ^{:line 298 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (count ^{:line 298 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (filterv ^{:line 298 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (fn [po] ^{:line 299 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (= ^{:line 299 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (purchaseorder-status po) "cancelled")) spos))]
  ^{:line 301 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (if ^{:line 301 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (= total 0) 0 ^{:line 301 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (quot ^{:line 301 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (* cancelled 100) total))))

^{:line 304 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (defn supplier-completed-spend [pos supplier-id]
  ^{:line 305 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (reduce ^{:line 305 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (fn [acc po] ^{:line 305 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (+ acc ^{:line 305 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (purchaseorder-total po))) 0 ^{:line 307 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (filterv ^{:line 307 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (fn [po] ^{:line 307 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (= ^{:line 307 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (purchaseorder-status po) "completed")) ^{:line 308 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (pos-for-supplier pos supplier-id))))

^{:line 315 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (defn overdue-pos [pos now]
  ^{:line 316 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (filterv ^{:line 316 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (fn [po] ^{:line 317 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (and ^{:line 317 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (po-open? po) ^{:line 318 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (< ^{:line 318 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (purchaseorder-expected-at po) now))) pos))

^{:line 322 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (defn overdue-count [pos now]
  ^{:line 323 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (count ^{:line 323 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (overdue-pos pos now)))

^{:line 326 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (defn overdue-total [pos now]
  ^{:line 327 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (reduce ^{:line 327 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (fn [acc po] ^{:line 327 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (+ acc ^{:line 327 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (purchaseorder-total po))) 0 ^{:line 329 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (overdue-pos pos now)))

^{:line 332 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (defn po-days-overdue [po now]
  ^{:line 333 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (let [diff ^{:line 333 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (- now ^{:line 333 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (purchaseorder-expected-at po))]
  ^{:line 334 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (if ^{:line 334 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (> diff 0) ^{:line 334 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (quot diff 86400) 0)))

^{:line 343 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (defn auto-reorder-lines [levels products]
  ^{:line 344 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (let [needed ^{:line 344 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (inv/reorder-needed levels)]
  ^{:line 345 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (mapv ^{:line 345 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (fn [sl] ^{:line 346 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (let [prod-id ^{:line 346 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (inv/stocklevel-product-id sl)
   qty ^{:line 347 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (inv/reorder-quantity sl)
   prod ^{:line 348 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (cat/find-product-by-id products prod-id)
   cost ^{:line 349 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (if ^{:line 349 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (nil? prod) 0 ^{:line 349 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (cat/product-unit-cost prod))]
  ^{:line 350 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (->POLine 0 prod-id qty cost))) needed)))

^{:line 354 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (defn auto-reorder-cost [levels products]
  ^{:line 355 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (po-total-from-lines ^{:line 355 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (auto-reorder-lines levels products)))

^{:line 358 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (defn auto-reorder-product-count [levels]
  ^{:line 359 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (count ^{:line 359 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (inv/reorder-needed levels)))

^{:line 366 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (defn total-procurement-spend [pos]
  ^{:line 367 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (reduce ^{:line 367 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (fn [acc po] ^{:line 367 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (+ acc ^{:line 367 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (purchaseorder-total po))) 0 ^{:line 369 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (filterv ^{:line 369 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (fn [po] ^{:line 369 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (= ^{:line 369 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (purchaseorder-status po) "completed")) pos)))

^{:line 373 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (defn open-procurement-value [pos]
  ^{:line 374 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (reduce ^{:line 374 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (fn [acc po] ^{:line 374 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (+ acc ^{:line 374 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (purchaseorder-total po))) 0 ^{:line 376 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (filterv po-open? pos)))

^{:line 379 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (defn gross-procurement-value [pos]
  ^{:line 380 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (reduce ^{:line 380 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (fn [acc po] ^{:line 380 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (+ acc ^{:line 380 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (purchaseorder-total po))) 0 pos))

^{:line 383 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (defn avg-po-value [pos]
  ^{:line 384 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (let [cnt ^{:line 384 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (count pos)]
  ^{:line 385 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (if ^{:line 385 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (= cnt 0) 0 ^{:line 386 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (quot ^{:line 386 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (gross-procurement-value pos) cnt))))

^{:line 389 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (defn period-procurement-spend [pos start end]
  ^{:line 391 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (reduce ^{:line 391 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (fn [acc po] ^{:line 391 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (+ acc ^{:line 391 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (purchaseorder-total po))) 0 ^{:line 393 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (filterv ^{:line 393 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (fn [po] ^{:line 394 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (and ^{:line 394 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (= ^{:line 394 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (purchaseorder-status po) "completed") ^{:line 395 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (>= ^{:line 395 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (purchaseorder-created-at po) start) ^{:line 396 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (<= ^{:line 396 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (purchaseorder-created-at po) end))) pos)))

^{:line 405 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (defn avg-lead-time-actual [pos receipts]
  ^{:line 406 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (let [completed ^{:line 406 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (filterv ^{:line 406 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (fn [po] ^{:line 407 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (= ^{:line 407 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (purchaseorder-status po) "completed")) pos)
   with-receipt ^{:line 409 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (filterv ^{:line 410 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (fn [po] ^{:line 411 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (not ^{:line 411 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (empty? ^{:line 411 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (receipts-for-po receipts ^{:line 413 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (purchaseorder-id po))))) completed)]
  ^{:line 415 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (if ^{:line 415 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (empty? with-receipt) 0 ^{:line 416 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (let [total-days ^{:line 417 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (reduce ^{:line 418 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (fn [acc po] ^{:line 419 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (let [po-receipts ^{:line 419 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (receipts-for-po receipts ^{:line 420 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (purchaseorder-id po))
   first-receipt ^{:line 421 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (first po-receipts)
   elapsed ^{:line 422 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (- ^{:line 422 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (goodsreceipt-received-at first-receipt) ^{:line 423 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (purchaseorder-created-at po))
   days ^{:line 424 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (quot elapsed 86400)]
  ^{:line 425 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (+ acc days))) 0 with-receipt)]
  ^{:line 427 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (quot total-days ^{:line 427 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (count with-receipt))))))

^{:line 431 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (defn po-actual-lead-days [po receipts]
  ^{:line 432 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (let [po-receipts ^{:line 432 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (receipts-for-po receipts ^{:line 432 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (purchaseorder-id po))]
  ^{:line 433 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (if ^{:line 433 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (empty? po-receipts) 0 ^{:line 434 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (let [first-receipt ^{:line 434 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (first po-receipts)
   elapsed ^{:line 435 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (- ^{:line 435 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (goodsreceipt-received-at first-receipt) ^{:line 436 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (purchaseorder-created-at po))]
  ^{:line 437 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (quot elapsed 86400)))))

^{:line 441 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (defn po-lead-variance-days [po receipts]
  ^{:line 442 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (let [actual ^{:line 442 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (po-actual-lead-days po receipts)
   expected ^{:line 443 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (po-expected-lead-days po)]
  ^{:line 444 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (- actual expected)))

^{:line 447 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (defn max-lead-time-actual [pos receipts]
  ^{:line 448 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (let [completed ^{:line 448 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (filterv ^{:line 448 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (fn [po] ^{:line 449 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (= ^{:line 449 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (purchaseorder-status po) "completed")) pos)
   with-receipt ^{:line 451 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (filterv ^{:line 452 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (fn [po] ^{:line 453 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (not ^{:line 453 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (empty? ^{:line 453 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (receipts-for-po receipts ^{:line 455 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (purchaseorder-id po))))) completed)]
  ^{:line 457 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (if ^{:line 457 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (empty? with-receipt) 0 ^{:line 458 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (reduce ^{:line 458 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (fn [mx po] ^{:line 459 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (let [days ^{:line 459 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (po-actual-lead-days po receipts)]
  ^{:line 460 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (if ^{:line 460 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (> days mx) days mx))) 0 with-receipt))))

^{:line 468 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (defn po-summary [po]
  ^{:line 469 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (str "PO#" ^{:line 469 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (purchaseorder-id po) " supplier:" ^{:line 470 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (purchaseorder-supplier-id po) " status:" ^{:line 471 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (purchaseorder-status po) " total:" ^{:line 472 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (purchaseorder-total po)))

^{:line 475 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (defn poline-summary [line]
  ^{:line 476 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (str "POLine po:" ^{:line 476 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (poline-po-id line) " product:" ^{:line 477 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (poline-product-id line) " qty:" ^{:line 478 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (poline-quantity line) " @" ^{:line 479 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (poline-unit-cost line) " = " ^{:line 480 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (poline-total line)))

^{:line 483 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (defn receipt-summary [r]
  ^{:line 484 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (str "GR#" ^{:line 484 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (goodsreceipt-id r) " po:" ^{:line 485 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (goodsreceipt-po-id r) " wh:" ^{:line 486 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (goodsreceipt-warehouse-id r) " lines:" ^{:line 487 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (goodsreceipt-line-count r)))

^{:line 490 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (defn po-detail [po lines products]
  ^{:line 492 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (let [po-lines ^{:line 492 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (lines-for-po lines ^{:line 492 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (purchaseorder-id po))
   line-strs ^{:line 493 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (mapv ^{:line 493 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (fn [line] ^{:line 494 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (let [prod ^{:line 494 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (cat/find-product-by-id products ^{:line 496 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (poline-product-id line))
   pname ^{:line 497 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (if ^{:line 497 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (nil? prod) "unknown" ^{:line 498 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (cat/product-name prod))]
  ^{:line 499 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (str "  " pname " qty:" ^{:line 500 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (poline-quantity line) " @" ^{:line 501 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (poline-unit-cost line)))) po-lines)]
  ^{:line 503 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (str ^{:line 503 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (po-summary po) "\n" ^{:line 504 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (reduce ^{:line 504 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (fn [acc s] ^{:line 504 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (str acc s "\n")) "" line-strs))))

^{:line 511 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (defn enrich-lines [lines products levels]
  ^{:line 513 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (mapv ^{:line 513 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (fn [line] ^{:line 514 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (let [prod-id ^{:line 514 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (poline-product-id line)
   prod ^{:line 515 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (cat/find-product-by-id products prod-id)
   pname ^{:line 516 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (if ^{:line 516 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (nil? prod) "unknown" ^{:line 516 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (cat/product-name prod))
   stock ^{:line 517 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (inv/total-stock-for-product levels prod-id)]
  ^{:line 518 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} {:po-id ^{:line 518 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (poline-po-id line) :product-id prod-id :product-name pname :quantity ^{:line 518 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (poline-quantity line) :unit-cost ^{:line 518 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (poline-unit-cost line) :line-total ^{:line 518 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (poline-total line) :current-stock stock})) lines))

^{:line 528 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (defn orphan-line-product-ids [lines products]
  ^{:line 529 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (filterv ^{:line 529 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (fn [pid] ^{:line 529 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (nil? ^{:line 529 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (cat/find-product-by-id products pid))) ^{:line 530 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (unique-products-in-lines lines)))

^{:line 537 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (defn po-count-by-status [pos]
  ^{:line 538 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} {:pending ^{:line 538 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (count ^{:line 538 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (pending-pos pos)) :approved ^{:line 538 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (count ^{:line 538 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (approved-pos pos)) :completed ^{:line 538 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (count ^{:line 538 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (completed-pos pos)) :cancelled ^{:line 538 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (count ^{:line 538 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (cancelled-pos pos))})

^{:line 544 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (defn total-line-count [lines]
  ^{:line 545 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (count lines))

^{:line 548 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (defn total-units-ordered [lines]
  ^{:line 549 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (reduce ^{:line 549 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (fn [acc line] ^{:line 549 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (+ acc ^{:line 549 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (poline-quantity line))) 0 lines))

^{:line 552 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (defn avg-line-value [lines]
  ^{:line 553 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (let [cnt ^{:line 553 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (count lines)]
  ^{:line 554 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (if ^{:line 554 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (= cnt 0) 0 ^{:line 555 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (quot ^{:line 555 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (po-total-from-lines lines) cnt))))

^{:line 558 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (defn avg-line-quantity [lines]
  ^{:line 559 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (let [cnt ^{:line 559 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (count lines)]
  ^{:line 560 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (if ^{:line 560 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (= cnt 0) 0 ^{:line 561 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (quot ^{:line 561 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (total-units-ordered lines) cnt))))

^{:line 564 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (defn largest-po [pos]
  ^{:line 565 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (if ^{:line 565 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (empty? pos) nil ^{:line 566 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (reduce ^{:line 566 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (fn [best po] ^{:line 567 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (if ^{:line 567 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (> ^{:line 567 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (purchaseorder-total po) ^{:line 568 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (purchaseorder-total best)) po best)) ^{:line 570 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (first pos) ^{:line 570 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (rest pos))))

^{:line 573 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (defn smallest-active-po [pos]
  ^{:line 574 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (let [active ^{:line 574 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (filterv ^{:line 574 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (fn [po] ^{:line 574 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (not= ^{:line 574 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (purchaseorder-status po) "cancelled")) pos)]
  ^{:line 576 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (if ^{:line 576 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (empty? active) nil ^{:line 577 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (reduce ^{:line 577 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (fn [best po] ^{:line 578 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (if ^{:line 578 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (< ^{:line 578 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (purchaseorder-total po) ^{:line 579 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (purchaseorder-total best)) po best)) ^{:line 581 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (first active) ^{:line 581 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (rest active)))))

^{:line 589 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (defn cost-variance [lines products product-id]
  ^{:line 591 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (let [avg-po-cost ^{:line 591 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (avg-unit-cost-for-product lines product-id)
   prod ^{:line 592 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (cat/find-product-by-id products product-id)
   cat-cost ^{:line 593 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (if ^{:line 593 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (nil? prod) 0 ^{:line 593 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (cat/product-unit-cost prod))]
  ^{:line 594 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (- avg-po-cost cat-cost)))

^{:line 597 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (defn products-over-catalog-cost [lines products]
  ^{:line 598 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (let [pids ^{:line 598 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (unique-products-in-lines lines)]
  ^{:line 599 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (filterv ^{:line 599 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (fn [pid] ^{:line 600 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (let [variance ^{:line 600 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (cost-variance lines products pid)]
  ^{:line 601 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (> variance 0))) pids)))

^{:line 606 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (defn warehouse-received-value [pos receipts lines warehouse-id]
  ^{:line 608 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (let [wh-receipts ^{:line 608 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (receipts-for-warehouse receipts warehouse-id)]
  ^{:line 609 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (reduce ^{:line 609 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (fn [acc r] ^{:line 610 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (let [po ^{:line 610 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (find-po-by-id pos ^{:line 610 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (goodsreceipt-po-id r))
   po-total ^{:line 611 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (if ^{:line 611 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (nil? po) 0 ^{:line 611 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (purchaseorder-total po))]
  ^{:line 612 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (+ acc po-total))) 0 wh-receipts)))

^{:line 620 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (defn procurement-dashboard [pos lines receipts now]
  ^{:line 622 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (let [total-spend ^{:line 622 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (total-procurement-spend pos)
   open-value ^{:line 623 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (open-procurement-value pos)
   overdue-cnt ^{:line 624 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (overdue-count pos now)
   overdue-val ^{:line 625 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (overdue-total pos now)
   avg-lead ^{:line 626 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (avg-lead-time-actual pos receipts)
   po-cnt ^{:line 627 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (count pos)
   line-cnt ^{:line 628 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (total-line-count lines)
   units ^{:line 629 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} (total-units-ordered lines)]
  ^{:line 630 :file "/home/tom/code/beagle/experiments/v2-inventory/trials/e7-beagle-run1/procurement.rkt"} {:total-spend total-spend :open-value open-value :overdue-count overdue-cnt :overdue-value overdue-val :avg-lead-time-days avg-lead :po-count po-cnt :line-count line-cnt :total-units units}))
