(ns employees
  (:require [catalog :as cat]
            [orders :as ord]))

^{:line 10 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defrecord Employee [id name department role hire-date active])

(defn employee-id [r] (:id r))

(defn employee-name [r] (:name r))

(defn employee-department [r] (:department r))

(defn employee-role [r] (:role r))

(defn employee-hire-date [r] (:hire-date r))

(defn employee-active [r] (:active r))

^{:line 13 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defrecord CommissionRule [id employee-id category-id rate-pct])

(defn commissionrule-id [r] (:id r))

(defn commissionrule-employee-id [r] (:employee-id r))

(defn commissionrule-category-id [r] (:category-id r))

(defn commissionrule-rate-pct [r] (:rate-pct r))

^{:line 16 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defrecord SalesTarget [id employee-id period target-amount actual-amount])

(defn salestarget-id [r] (:id r))

(defn salestarget-employee-id [r] (:employee-id r))

(defn salestarget-period [r] (:period r))

(defn salestarget-target-amount [r] (:target-amount r))

(defn salestarget-actual-amount [r] (:actual-amount r))

^{:line 21 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn find-employee-by-id [employees id]
  ^{:line 22 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (first ^{:line 22 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (filterv ^{:line 22 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (fn [e] ^{:line 22 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (= ^{:line 22 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employee-hire-date e) id)) employees)))

^{:line 24 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn active-employees [employees]
  ^{:line 25 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (filterv ^{:line 25 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (fn [e] ^{:line 25 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employee-active e)) employees))

^{:line 27 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn employees-by-department [employees dept]
  ^{:line 28 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (filterv ^{:line 28 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (fn [e] ^{:line 28 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (= ^{:line 28 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employee-department e) dept)) employees))

^{:line 30 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn employees-by-role [employees role]
  ^{:line 31 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (filterv ^{:line 31 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (fn [e] ^{:line 31 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (= ^{:line 31 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employee-role e) role)) employees))

^{:line 33 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn employee-tenure-days [employee now]
  ^{:line 34 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (quot ^{:line 34 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (- now ^{:line 34 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employee-hire-date employee)) 86400))

^{:line 36 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn senior-employees [employees now min-days]
  ^{:line 37 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (filterv ^{:line 37 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (fn [e] ^{:line 38 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (>= ^{:line 38 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employee-tenure-days e now) min-days)) employees))

^{:line 43 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn rules-for-employee [rules employee-id]
  ^{:line 44 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (filterv ^{:line 44 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (fn [r] ^{:line 44 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (= ^{:line 44 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (commissionrule-employee-id r) employee-id)) rules))

^{:line 46 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn commission-rate [rules employee-id category-id]
  ^{:line 47 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (let [matches ^{:line 47 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (filterv ^{:line 47 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (fn [r] ^{:line 48 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (and ^{:line 48 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (= ^{:line 48 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (commissionrule-employee-id r) employee-id) ^{:line 49 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (= ^{:line 49 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (commissionrule-category-id r) category-id))) rules)]
  ^{:line 51 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (if ^{:line 51 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (empty? matches) 0 ^{:line 53 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (commissionrule-rate-pct ^{:line 53 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (first matches)))))

^{:line 55 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn line-commission [rules employee-id product ol]
  ^{:line 57 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (let [cat-id ^{:line 57 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (cat/product-category-id product)
   rate ^{:line 58 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (commission-rate rules employee-id cat-id)
   amount ^{:line 59 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (ord/orderline-line-total ol)]
  ^{:line 60 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (quot ^{:line 60 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (* rate amount) 100)))

^{:line 62 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn order-commission [rules employee-id order products]
  ^{:line 64 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (let [lines ^{:line 64 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (ord/order-lines order)]
  ^{:line 65 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (reduce ^{:line 65 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (fn [acc ol] ^{:line 66 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (let [prod-id ^{:line 66 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (ord/orderline-product-id ol)
   product ^{:line 67 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (cat/find-product-by-id products prod-id)]
  ^{:line 68 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (if ^{:line 68 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (nil? product) acc ^{:line 70 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (+ acc ^{:line 70 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (line-commission rules employee-id product ol))))) 0 lines)))

^{:line 73 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn total-commission [rules employee-id orders products]
  ^{:line 75 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (reduce ^{:line 75 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (fn [acc o] ^{:line 76 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (+ acc ^{:line 76 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (order-commission rules (str employee-id) o products))) 0 orders))

^{:line 79 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn top-earner [rules employees orders products]
  ^{:line 81 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (let [actives ^{:line 81 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (active-employees employees)]
  ^{:line 82 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (if ^{:line 82 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (empty? actives) nil ^{:line 84 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (reduce ^{:line 84 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (fn [best e] ^{:line 85 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (let [best-comm ^{:line 85 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (total-commission rules ^{:line 85 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employee-id best) orders products)
   curr-comm ^{:line 86 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (total-commission rules ^{:line 86 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employee-id e) orders products)]
  ^{:line 87 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (if ^{:line 87 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (> curr-comm best-comm) e best))) ^{:line 88 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (first actives) ^{:line 88 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (rest actives)))))

^{:line 92 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn targets-for-employee [targets employee-id]
  ^{:line 93 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (filterv ^{:line 93 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (fn [t] ^{:line 93 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (= ^{:line 93 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (salestarget-employee-id t) employee-id)) targets))

^{:line 95 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn target-for-period [targets employee-id period]
  ^{:line 97 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (first ^{:line 97 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (filterv ^{:line 97 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (fn [t] ^{:line 98 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (and ^{:line 98 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (= ^{:line 98 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (salestarget-employee-id t) employee-id) ^{:line 99 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (= ^{:line 99 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (salestarget-period t) period))) targets)))

^{:line 102 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn target-achievement-pct [target]
  ^{:line 103 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (let [ta ^{:line 103 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (salestarget-target-amount target)]
  ^{:line 104 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (if ^{:line 104 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (= ta 0) 0 ^{:line 106 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (quot ^{:line 106 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (* ^{:line 106 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (salestarget-actual-amount target) 100) ta))))

^{:line 108 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn on-target? [target]
  ^{:line 109 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (>= ^{:line 109 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (target-achievement-pct target) 100))

^{:line 111 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn targets-met-count [targets employee-id]
  ^{:line 112 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (let [emp-targets ^{:line 112 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (targets-for-employee targets employee-id)]
  ^{:line 113 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (count ^{:line 113 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (filterv ^{:line 113 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (fn [t] ^{:line 113 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (on-target? t)) emp-targets))))

^{:line 115 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn update-actual [target amount]
  ^{:line 116 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (->SalesTarget ^{:line 116 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (salestarget-id target) ^{:line 117 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (salestarget-employee-id target) ^{:line 118 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (salestarget-period target) ^{:line 119 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (salestarget-target-amount target) amount))

^{:line 124 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn department-headcount [employees dept]
  ^{:line 125 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (count ^{:line 125 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employees-by-department employees dept)))

^{:line 127 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn department-total-commission [rules employees dept orders products]
  ^{:line 130 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (let [dept-emps ^{:line 130 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employees-by-department employees dept)]
  ^{:line 131 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (reduce ^{:line 131 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (fn [acc e] ^{:line 132 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (+ acc ^{:line 132 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (total-commission rules ^{:line 132 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employee-id e) orders products))) 0 dept-emps)))

^{:line 135 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn avg-commission-per-employee [rules employees orders products]
  ^{:line 137 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (let [actives ^{:line 137 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (active-employees employees)
   cnt ^{:line 138 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (count actives)]
  ^{:line 139 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (if ^{:line 139 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (= cnt 0) 0 ^{:line 141 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (let [total ^{:line 141 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (reduce ^{:line 141 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (fn [acc e] ^{:line 142 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (+ acc ^{:line 142 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (total-commission rules ^{:line 142 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employee-id e) orders products))) 0 actives)]
  ^{:line 145 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (quot total cnt)))))

^{:line 149 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn employee-summary [e]
  ^{:line 150 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (str ^{:line 150 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employee-name e) " (" ^{:line 150 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employee-department e) "/" ^{:line 150 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employee-role e) ")"))

^{:line 152 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn employee-detail [e now]
  ^{:line 153 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (str ^{:line 153 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employee-name e) " | Dept: " ^{:line 154 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employee-department e) " | Role: " ^{:line 155 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employee-role e) " | Tenure: " ^{:line 156 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employee-tenure-days e now) " days" " | Active: " ^{:line 157 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employee-active e)))

^{:line 161 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn valid-employee? [e]
  ^{:line 162 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (and ^{:line 162 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (> ^{:line 162 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employee-id e) 0) ^{:line 163 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (not= ^{:line 163 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employee-name e) "") ^{:line 164 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (not= ^{:line 164 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employee-department e) "") ^{:line 165 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (not= ^{:line 165 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employee-role e) "")))

^{:line 167 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn valid-commission-rule? [r]
  ^{:line 168 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (and ^{:line 168 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (> ^{:line 168 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (commissionrule-id r) 0) ^{:line 169 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (> ^{:line 169 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (commissionrule-employee-id r) 0) ^{:line 170 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (> ^{:line 170 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (commissionrule-category-id r) 0) ^{:line 171 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (> ^{:line 171 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (commissionrule-rate-pct r) 0) ^{:line 172 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (<= ^{:line 172 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (commissionrule-rate-pct r) 100)))

^{:line 174 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn valid-sales-target? [t]
  ^{:line 175 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (and ^{:line 175 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (> ^{:line 175 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (salestarget-id t) 0) ^{:line 176 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (> ^{:line 176 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (salestarget-employee-id t) 0) ^{:line 177 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (not= ^{:line 177 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (salestarget-period t) "") ^{:line 178 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (> ^{:line 178 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (salestarget-target-amount t) 0) ^{:line 179 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (>= ^{:line 179 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (salestarget-actual-amount t) 0)))

^{:line 183 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn employee-commission-breakdown [rules employee-id orders products]
  ^{:line 185 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (let [emp-rules ^{:line 185 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (rules-for-employee rules employee-id)]
  ^{:line 186 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (mapv ^{:line 186 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (fn [r] ^{:line 187 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (let [cat-id ^{:line 187 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (commissionrule-category-id r)
   rate ^{:line 188 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (commissionrule-rate-pct r)
   cat-commission ^{:line 189 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (reduce ^{:line 190 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (fn [acc o] ^{:line 191 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (let [lines ^{:line 191 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (ord/order-lines o)]
  ^{:line 192 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (+ acc ^{:line 192 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (reduce ^{:line 193 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (fn [a ol] ^{:line 194 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (let [prod-id ^{:line 194 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (ord/orderline-product-id ol)
   product ^{:line 195 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (cat/find-product-by-id products prod-id)]
  ^{:line 196 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (if ^{:line 196 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (nil? product) a ^{:line 198 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (if ^{:line 198 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (= ^{:line 198 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (cat/product-category-id product) cat-id) ^{:line 199 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (+ a ^{:line 199 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (quot ^{:line 199 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (* rate ^{:line 199 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (ord/orderline-line-total ol)) 100)) a)))) 0 lines)))) 0 orders)]
  ^{:line 203 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} {:category-id cat-id :rate rate :commission cat-commission})) emp-rules)))

^{:line 206 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn employee-top-category [rules employee-id orders products]
  ^{:line 208 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (let [breakdown ^{:line 208 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employee-commission-breakdown rules employee-id orders products)]
  ^{:line 209 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (if ^{:line 209 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (empty? breakdown) 0 ^{:line 211 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (let [best ^{:line 211 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (reduce ^{:line 211 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (fn [b item] ^{:line 212 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (if ^{:line 212 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (> ^{:line 212 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (:commission item) ^{:line 212 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (:commission b)) item b)) ^{:line 213 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (first breakdown) ^{:line 213 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (rest breakdown))]
  ^{:line 214 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (:category-id best)))))

^{:line 218 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn employee-target-summary [targets employee-id]
  ^{:line 219 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (let [emp-targets ^{:line 219 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (targets-for-employee targets employee-id)
   total-target ^{:line 220 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (reduce ^{:line 220 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (fn [acc t] ^{:line 220 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (+ acc ^{:line 220 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (salestarget-target-amount t))) 0 emp-targets)
   total-actual ^{:line 222 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (reduce ^{:line 222 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (fn [acc t] ^{:line 222 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (+ acc ^{:line 222 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (salestarget-actual-amount t))) 0 emp-targets)
   met ^{:line 224 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (targets-met-count targets employee-id)]
  ^{:line 225 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} {:total-target total-target :total-actual total-actual :targets-met met :total-targets ^{:line 225 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (count emp-targets)}))

^{:line 230 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn best-performing-period [targets employee-id]
  ^{:line 231 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (let [emp-targets ^{:line 231 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (targets-for-employee targets employee-id)]
  ^{:line 232 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (if ^{:line 232 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (empty? emp-targets) nil ^{:line 234 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (let [best ^{:line 234 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (reduce ^{:line 234 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (fn [b t] ^{:line 235 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (if ^{:line 235 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (> ^{:line 235 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (target-achievement-pct t) ^{:line 236 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (target-achievement-pct b)) t b)) ^{:line 238 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (first emp-targets) ^{:line 238 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (rest emp-targets))]
  ^{:line 239 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (salestarget-period best)))))

^{:line 241 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn worst-performing-period [targets employee-id]
  ^{:line 242 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (let [emp-targets ^{:line 242 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (targets-for-employee targets employee-id)]
  ^{:line 243 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (if ^{:line 243 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (empty? emp-targets) nil ^{:line 245 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (let [worst ^{:line 245 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (reduce ^{:line 245 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (fn [b t] ^{:line 246 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (if ^{:line 246 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (< ^{:line 246 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (target-achievement-pct t) ^{:line 247 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (target-achievement-pct b)) t b)) ^{:line 249 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (first emp-targets) ^{:line 249 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (rest emp-targets))]
  ^{:line 250 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (salestarget-period worst)))))

^{:line 254 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn department-avg-tenure [employees dept now]
  ^{:line 255 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (let [dept-emps ^{:line 255 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employees-by-department employees dept)
   cnt ^{:line 256 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (count dept-emps)]
  ^{:line 257 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (if ^{:line 257 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (= cnt 0) 0 ^{:line 259 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (quot ^{:line 259 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (reduce ^{:line 259 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (fn [acc e] ^{:line 260 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (+ acc ^{:line 260 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employee-tenure-days e now))) 0 dept-emps) cnt))))

^{:line 264 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn department-active-count [employees dept]
  ^{:line 265 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (count ^{:line 265 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (filterv ^{:line 265 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (fn [e] ^{:line 265 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (and ^{:line 265 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (= ^{:line 265 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employee-department e) dept) ^{:line 266 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employee-active e))) employees)))

^{:line 269 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn department-active-pct [employees dept]
  ^{:line 270 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (let [total ^{:line 270 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (department-headcount employees dept)]
  ^{:line 271 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (if ^{:line 271 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (= total 0) 0 ^{:line 273 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (quot ^{:line 273 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (* ^{:line 273 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (department-active-count employees dept) 100) total))))

^{:line 277 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn deactivate-employee [employees target-id]
  ^{:line 278 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (mapv ^{:line 278 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (fn [e] ^{:line 279 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (if ^{:line 279 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (= ^{:line 279 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employee-id e) target-id) ^{:line 280 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (->Employee ^{:line 280 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employee-id e) ^{:line 280 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employee-name e) ^{:line 281 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employee-department e) ^{:line 281 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employee-role e) ^{:line 282 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employee-hire-date e) false) e)) employees))

^{:line 286 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn activate-employee [employees target-id]
  ^{:line 287 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (mapv ^{:line 287 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (fn [e] ^{:line 288 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (if ^{:line 288 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (= ^{:line 288 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employee-id e) target-id) ^{:line 289 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (->Employee ^{:line 289 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employee-id e) ^{:line 289 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employee-name e) ^{:line 290 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employee-department e) ^{:line 290 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employee-role e) ^{:line 291 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employee-hire-date e) true) e)) employees))

^{:line 295 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn change-department [employee new-dept]
  ^{:line 296 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (->Employee ^{:line 296 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employee-id employee) ^{:line 296 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employee-name employee) new-dept ^{:line 297 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employee-role employee) ^{:line 298 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employee-hire-date employee) ^{:line 298 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employee-active employee)))

^{:line 300 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn change-role [employee new-role]
  ^{:line 301 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (->Employee ^{:line 301 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employee-id employee) ^{:line 301 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employee-name employee) ^{:line 302 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employee-department employee) new-role ^{:line 303 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employee-hire-date employee) ^{:line 303 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employee-active employee)))

^{:line 307 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn add-commission-rule [rules rule]
  ^{:line 308 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (conj rules rule))

^{:line 310 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn remove-commission-rule [rules rule-id]
  ^{:line 311 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (filterv ^{:line 311 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (fn [r] ^{:line 311 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (not= ^{:line 311 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (commissionrule-id r) rule-id)) rules))

^{:line 313 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn update-commission-rate [rules rule-id new-rate]
  ^{:line 314 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (mapv ^{:line 314 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (fn [r] ^{:line 315 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (if ^{:line 315 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (= ^{:line 315 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (commissionrule-id r) rule-id) ^{:line 316 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (->CommissionRule ^{:line 316 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (commissionrule-id r) ^{:line 317 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (commissionrule-employee-id r) ^{:line 318 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (commissionrule-category-id r) new-rate) r)) rules))

^{:line 325 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn employee-order-count [employee-id orders]
  ^{:line 326 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (count orders))

^{:line 328 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn employee-revenue [rules employee-id orders products]
  ^{:line 330 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (total-commission rules employee-id orders products))

^{:line 334 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn rank-by-commission [rules employees orders products]
  ^{:line 336 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (let [actives ^{:line 336 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (active-employees employees)]
  ^{:line 337 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (reverse ^{:line 337 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (sort-by ^{:line 337 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (fn [e] ^{:line 338 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (total-commission rules ^{:line 338 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employee-id e) orders products)) actives))))

^{:line 341 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn rank-by-tenure [employees now]
  ^{:line 342 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (reverse ^{:line 342 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (sort-by ^{:line 342 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (fn [e] ^{:line 342 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employee-tenure-days e now)) employees)))

^{:line 345 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn commission-leaderboard [rules employees orders products]
  ^{:line 347 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (let [ranked ^{:line 347 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (rank-by-commission rules employees orders products)]
  ^{:line 348 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (mapv ^{:line 348 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (fn [e] ^{:line 349 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} {:employee-id ^{:line 349 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employee-id e) :name ^{:line 349 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employee-name e) :commission ^{:line 349 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (total-commission rules ^{:line 349 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employee-id e) orders products)}) ranked)))

^{:line 356 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn total-headcount [employees]
  ^{:line 357 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (count employees))

^{:line 359 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn active-headcount [employees]
  ^{:line 360 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (count ^{:line 360 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (active-employees employees)))

^{:line 362 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn turnover-rate-pct [employees]
  ^{:line 363 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (let [total ^{:line 363 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (total-headcount employees)]
  ^{:line 364 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (if ^{:line 364 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (= total 0) 0 ^{:line 366 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (let [inactive ^{:line 366 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (- total ^{:line 366 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (active-headcount employees))]
  ^{:line 367 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (quot ^{:line 367 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (* inactive 100) total)))))

^{:line 369 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn unique-departments [employees]
  ^{:line 370 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (distinct ^{:line 370 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (mapv employee-department employees)))

^{:line 372 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn unique-roles [employees]
  ^{:line 373 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (distinct ^{:line 373 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (mapv employee-role employees)))

^{:line 375 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn department-roster [employees dept]
  ^{:line 376 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (let [dept-emps ^{:line 376 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employees-by-department employees dept)]
  ^{:line 377 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (mapv ^{:line 377 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (fn [e] ^{:line 378 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} {:id ^{:line 378 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employee-id e) :name ^{:line 378 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employee-name e) :role ^{:line 378 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employee-role e) :active ^{:line 378 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employee-active e)}) dept-emps)))

^{:line 386 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn target-gap [target]
  ^{:line 387 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (let [diff ^{:line 387 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (- ^{:line 387 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (salestarget-target-amount target) ^{:line 388 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (salestarget-actual-amount target))]
  ^{:line 389 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (if ^{:line 389 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (> diff 0) diff 0)))

^{:line 391 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn target-surplus [target]
  ^{:line 392 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (let [diff ^{:line 392 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (- ^{:line 392 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (salestarget-actual-amount target) ^{:line 393 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (salestarget-target-amount target))]
  ^{:line 394 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (if ^{:line 394 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (> diff 0) diff 0)))

^{:line 396 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn employee-total-target [targets employee-id]
  ^{:line 397 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (let [emp-targets ^{:line 397 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (targets-for-employee targets employee-id)]
  ^{:line 398 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (reduce ^{:line 398 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (fn [acc t] ^{:line 398 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (+ acc ^{:line 398 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (salestarget-target-amount t))) 0 emp-targets)))

^{:line 400 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn employee-total-actual [targets employee-id]
  ^{:line 401 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (let [emp-targets ^{:line 401 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (targets-for-employee targets employee-id)]
  ^{:line 402 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (reduce ^{:line 402 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (fn [acc t] ^{:line 402 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (+ acc ^{:line 402 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (salestarget-actual-amount t))) 0 emp-targets)))

^{:line 404 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn employee-total-gap [targets employee-id]
  ^{:line 405 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (let [emp-targets ^{:line 405 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (targets-for-employee targets employee-id)]
  ^{:line 406 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (reduce ^{:line 406 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (fn [acc t] ^{:line 406 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (+ acc ^{:line 406 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (target-gap t))) 0 emp-targets)))

^{:line 408 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn employee-total-surplus [targets employee-id]
  ^{:line 409 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (let [emp-targets ^{:line 409 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (targets-for-employee targets employee-id)]
  ^{:line 410 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (reduce ^{:line 410 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (fn [acc t] ^{:line 410 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (+ acc ^{:line 410 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (target-surplus t))) 0 emp-targets)))

^{:line 412 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn employee-overall-achievement-pct [targets employee-id]
  ^{:line 413 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (let [total-tgt ^{:line 413 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employee-total-target targets employee-id)]
  ^{:line 414 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (if ^{:line 414 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (= total-tgt 0) 0 ^{:line 416 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (quot ^{:line 416 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (* ^{:line 416 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employee-total-actual targets employee-id) 100) total-tgt))))

^{:line 420 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn employees-above-commission [rules employees orders products threshold]
  ^{:line 423 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (filterv ^{:line 423 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (fn [e] ^{:line 424 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (>= ^{:line 424 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (total-commission rules ^{:line 424 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employee-id e) orders products) threshold)) ^{:line 425 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (active-employees employees)))

^{:line 427 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn employees-below-commission [rules employees orders products threshold]
  ^{:line 430 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (filterv ^{:line 430 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (fn [e] ^{:line 431 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (< ^{:line 431 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (total-commission rules ^{:line 431 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employee-id e) orders products) threshold)) ^{:line 432 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (active-employees employees)))

^{:line 434 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn commission-spread [rules employees orders products]
  ^{:line 436 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (let [actives ^{:line 436 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (active-employees employees)]
  ^{:line 437 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (if ^{:line 437 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (empty? actives) 0 ^{:line 439 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (let [commissions ^{:line 439 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (mapv ^{:line 439 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (fn [e] ^{:line 440 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (total-commission rules ^{:line 440 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employee-id e) orders products)) actives)
   max-c ^{:line 443 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (apply max commissions)
   min-c ^{:line 444 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (apply min commissions)]
  ^{:line 445 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (- max-c min-c)))))

^{:line 447 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn median-commission [rules employees orders products]
  ^{:line 449 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (let [actives ^{:line 449 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (active-employees employees)]
  ^{:line 450 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (if ^{:line 450 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (empty? actives) 0 ^{:line 452 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (let [commissions ^{:line 452 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (sort ^{:line 452 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (mapv ^{:line 452 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (fn [e] ^{:line 453 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (total-commission rules ^{:line 453 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employee-id e) orders products)) actives))
   cnt ^{:line 456 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (count commissions)
   mid ^{:line 457 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (quot cnt 2)]
  ^{:line 458 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (nth commissions mid)))))

^{:line 462 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn category-total-commission [rules employees category-id orders products]
  ^{:line 465 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (let [actives ^{:line 465 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (active-employees employees)]
  ^{:line 466 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (reduce ^{:line 466 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (fn [acc e] ^{:line 467 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (let [rate ^{:line 467 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (commission-rate rules ^{:line 467 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employee-id e) category-id)]
  ^{:line 468 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (+ acc ^{:line 468 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (reduce ^{:line 469 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (fn [a o] ^{:line 470 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (let [lines ^{:line 470 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (ord/order-lines o)]
  ^{:line 471 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (+ a ^{:line 471 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (reduce ^{:line 472 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (fn [inner ol] ^{:line 473 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (let [prod-id ^{:line 473 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (ord/orderline-product-id ol)
   product ^{:line 474 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (cat/find-product-by-id products prod-id)]
  ^{:line 475 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (if ^{:line 475 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (nil? product) inner ^{:line 477 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (if ^{:line 477 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (= ^{:line 477 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (cat/product-category-id product) category-id) ^{:line 478 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (+ inner ^{:line 478 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (quot ^{:line 478 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (* rate ^{:line 478 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (ord/orderline-line-total ol)) 100)) inner)))) 0 lines)))) 0 orders)))) 0 actives)))

^{:line 484 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn category-avg-commission-rate [rules category-id]
  ^{:line 485 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (let [matching ^{:line 485 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (filterv ^{:line 485 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (fn [r] ^{:line 485 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (= ^{:line 485 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (commissionrule-category-id r) category-id)) rules)
   cnt ^{:line 487 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (count matching)]
  ^{:line 488 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (if ^{:line 488 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (= cnt 0) 0 ^{:line 490 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (quot ^{:line 490 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (reduce ^{:line 490 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (fn [acc r] ^{:line 490 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (+ acc ^{:line 490 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (commissionrule-rate-pct r))) 0 matching) cnt))))

^{:line 494 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn categories-with-rules [rules]
  ^{:line 495 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (distinct ^{:line 495 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (mapv commissionrule-category-id rules)))

^{:line 497 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn rules-for-category [rules category-id]
  ^{:line 498 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (filterv ^{:line 498 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (fn [r] ^{:line 498 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (= ^{:line 498 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (commissionrule-category-id r) category-id)) rules))

^{:line 500 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn category-rule-count [rules category-id]
  ^{:line 501 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (count ^{:line 501 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (rules-for-category rules category-id)))

^{:line 505 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn performance-score [rules targets employee-id orders products]
  ^{:line 507 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (let [comm ^{:line 507 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (total-commission rules employee-id orders products)
   achievement ^{:line 508 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employee-overall-achievement-pct targets employee-id)
   met ^{:line 509 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (targets-met-count targets employee-id)]
  ^{:line 510 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (+ ^{:line 510 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (quot comm 100) ^{:line 510 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (* achievement 2) ^{:line 510 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (* met 500))))

^{:line 512 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn rank-by-performance [rules targets employees orders products]
  ^{:line 514 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (let [actives ^{:line 514 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (active-employees employees)]
  ^{:line 515 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (reverse ^{:line 515 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (sort-by ^{:line 515 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (fn [e] ^{:line 516 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (performance-score rules targets ^{:line 516 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employee-id e) orders products)) actives))))

^{:line 520 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn top-performers [rules targets employees orders products n]
  ^{:line 522 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (let [ranked ^{:line 522 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (rank-by-performance rules targets employees orders products)]
  ^{:line 523 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (vec ^{:line 523 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (take n ranked))))

^{:line 525 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn bottom-performers [rules targets employees orders products n]
  ^{:line 527 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (let [ranked ^{:line 527 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (rank-by-performance rules targets employees orders products)]
  ^{:line 528 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (vec ^{:line 528 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (take n ^{:line 528 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (reverse ranked)))))

^{:line 530 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn performance-report [rules targets employees orders products]
  ^{:line 532 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (let [actives ^{:line 532 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (active-employees employees)]
  ^{:line 533 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (mapv ^{:line 533 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (fn [e] ^{:line 534 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (let [eid ^{:line 534 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employee-id e)]
  ^{:line 535 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} {:employee-id eid :name ^{:line 535 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employee-name e) :department ^{:line 535 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employee-department e) :commission ^{:line 535 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (total-commission rules eid orders products) :achievement-pct ^{:line 535 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employee-overall-achievement-pct targets eid) :targets-met ^{:line 535 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (targets-met-count targets eid) :score ^{:line 535 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (performance-score rules targets eid orders products)})) actives)))

^{:line 546 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn department-commission-breakdown [rules employees dept orders products]
  ^{:line 549 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (let [dept-emps ^{:line 549 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employees-by-department employees dept)]
  ^{:line 550 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (mapv ^{:line 550 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (fn [e] ^{:line 551 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} {:employee-id ^{:line 551 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employee-id e) :name ^{:line 551 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employee-name e) :commission ^{:line 551 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (total-commission rules ^{:line 551 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employee-id e) orders products)}) dept-emps)))

^{:line 556 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn department-avg-commission [rules employees dept orders products]
  ^{:line 559 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (let [dept-emps ^{:line 559 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employees-by-department employees dept)
   cnt ^{:line 560 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (count dept-emps)]
  ^{:line 561 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (if ^{:line 561 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (= cnt 0) 0 ^{:line 563 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (quot ^{:line 563 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (department-total-commission rules employees dept orders products) cnt))))

^{:line 565 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn department-commission-spread [rules employees dept orders products]
  ^{:line 568 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (let [dept-emps ^{:line 568 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employees-by-department employees dept)]
  ^{:line 569 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (if ^{:line 569 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (empty? dept-emps) 0 ^{:line 571 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (let [commissions ^{:line 571 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (mapv ^{:line 571 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (fn [e] ^{:line 572 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (total-commission rules ^{:line 572 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employee-id e) orders products)) dept-emps)
   max-c ^{:line 575 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (apply max commissions)
   min-c ^{:line 576 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (apply min commissions)]
  ^{:line 577 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (- max-c min-c)))))

^{:line 581 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn newest-employee [employees]
  ^{:line 582 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (if ^{:line 582 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (empty? employees) nil ^{:line 584 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (reduce ^{:line 584 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (fn [newest e] ^{:line 585 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (if ^{:line 585 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (> ^{:line 585 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employee-hire-date e) ^{:line 585 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employee-hire-date newest)) e newest)) ^{:line 587 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (first employees) ^{:line 587 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (rest employees))))

^{:line 589 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn oldest-employee [employees]
  ^{:line 590 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (if ^{:line 590 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (empty? employees) nil ^{:line 592 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (reduce ^{:line 592 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (fn [oldest e] ^{:line 593 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (if ^{:line 593 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (< ^{:line 593 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employee-hire-date e) ^{:line 593 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employee-hire-date oldest)) e oldest)) ^{:line 595 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (first employees) ^{:line 595 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (rest employees))))

^{:line 597 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn avg-tenure-days [employees now]
  ^{:line 598 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (let [cnt ^{:line 598 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (count employees)]
  ^{:line 599 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (if ^{:line 599 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (= cnt 0) 0 ^{:line 601 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (quot ^{:line 601 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (reduce ^{:line 601 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (fn [acc e] ^{:line 602 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (+ acc ^{:line 602 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employee-tenure-days e now))) 0 employees) cnt))))

^{:line 606 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn tenure-spread-days [employees now]
  ^{:line 607 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (if ^{:line 607 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (empty? employees) 0 ^{:line 609 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (let [tenures ^{:line 609 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (mapv ^{:line 609 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (fn [e] ^{:line 609 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employee-tenure-days e now)) employees)
   max-t ^{:line 611 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (apply max tenures)
   min-t ^{:line 612 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (apply min tenures)]
  ^{:line 613 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (- max-t min-t))))

^{:line 615 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn employees-hired-in-period [employees start end]
  ^{:line 616 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (filterv ^{:line 616 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (fn [e] ^{:line 617 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (and ^{:line 617 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (>= ^{:line 617 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employee-hire-date e) start) ^{:line 618 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (<= ^{:line 618 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employee-hire-date e) end))) employees))

^{:line 621 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn hire-count-in-period [employees start end]
  ^{:line 622 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (count ^{:line 622 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employees-hired-in-period employees start end)))

^{:line 626 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn employee-order-revenue [rules employee-id order products]
  ^{:line 628 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (order-commission rules employee-id order products))

^{:line 630 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn employee-avg-order-commission [rules employee-id orders products]
  ^{:line 632 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (let [cnt ^{:line 632 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (count orders)]
  ^{:line 633 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (if ^{:line 633 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (= cnt 0) 0 ^{:line 635 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (quot ^{:line 635 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (total-commission rules employee-id orders products) cnt))))

^{:line 637 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn employee-highest-commission-order [rules employee-id orders products]
  ^{:line 639 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (if ^{:line 639 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (empty? orders) nil ^{:line 641 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (reduce ^{:line 641 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (fn [best o] ^{:line 642 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (let [best-comm ^{:line 642 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (order-commission rules employee-id best products)
   curr-comm ^{:line 643 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (order-commission rules employee-id o products)]
  ^{:line 644 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (if ^{:line 644 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (> curr-comm best-comm) o best))) ^{:line 645 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (first orders) ^{:line 645 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (rest orders))))

^{:line 647 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn employee-zero-commission-orders [rules employee-id orders products]
  ^{:line 649 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (filterv ^{:line 649 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (fn [o] ^{:line 650 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (= ^{:line 650 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (order-commission rules employee-id o products) 0)) orders))

^{:line 655 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn increment-actual [target amount]
  ^{:line 656 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (->SalesTarget ^{:line 656 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (salestarget-id target) ^{:line 657 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (salestarget-employee-id target) ^{:line 658 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (salestarget-period target) ^{:line 659 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (salestarget-target-amount target) ^{:line 660 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (+ ^{:line 660 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (salestarget-actual-amount target) amount)))

^{:line 662 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn update-target-amount [target new-target]
  ^{:line 663 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (->SalesTarget ^{:line 663 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (salestarget-id target) ^{:line 664 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (salestarget-employee-id target) ^{:line 665 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (salestarget-period target) new-target ^{:line 667 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (salestarget-actual-amount target)))

^{:line 669 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn remaining-to-target [target]
  ^{:line 670 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (let [gap ^{:line 670 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (target-gap target)]
  gap))

^{:line 673 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn target-completion-rate [targets employee-id]
  ^{:line 674 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (let [emp-targets ^{:line 674 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (targets-for-employee targets employee-id)
   cnt ^{:line 675 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (count emp-targets)]
  ^{:line 676 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (if ^{:line 676 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (= cnt 0) 0 ^{:line 678 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (quot ^{:line 678 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (* ^{:line 678 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (targets-met-count targets employee-id) 100) cnt))))

^{:line 682 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn employee-full-report [rules targets employee orders products now]
  ^{:line 684 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (let [eid ^{:line 684 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employee-id employee)]
  ^{:line 685 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} {:employee-id eid :name ^{:line 685 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employee-name employee) :department ^{:line 685 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employee-department employee) :role ^{:line 685 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employee-role employee) :tenure-days ^{:line 685 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employee-tenure-days employee now) :active ^{:line 685 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employee-active employee) :total-commission ^{:line 685 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (total-commission rules eid orders products) :achievement-pct ^{:line 685 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employee-overall-achievement-pct targets eid) :targets-met ^{:line 685 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (targets-met-count targets eid) :performance-score ^{:line 685 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (performance-score rules targets eid orders products)}))

^{:line 696 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn department-full-report [rules targets employees dept orders products now]
  ^{:line 699 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (let [dept-emps ^{:line 699 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employees-by-department employees dept)]
  ^{:line 700 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} {:department dept :headcount ^{:line 700 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (count dept-emps) :active-count ^{:line 700 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (department-active-count employees dept) :avg-tenure ^{:line 700 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (department-avg-tenure employees dept now) :total-commission ^{:line 700 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (department-total-commission rules employees dept orders products) :avg-commission ^{:line 700 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (department-avg-commission rules employees dept orders products)}))

^{:line 709 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (defn company-summary [rules targets employees orders products now]
  ^{:line 711 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (let [actives ^{:line 711 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (active-employees employees)
   total-comm ^{:line 712 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (reduce ^{:line 712 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (fn [acc e] ^{:line 713 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (+ acc ^{:line 713 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (total-commission rules ^{:line 713 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employee-id e) orders products))) 0 actives)
   total-met ^{:line 716 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (reduce ^{:line 716 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (fn [acc e] ^{:line 717 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (+ acc ^{:line 717 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (targets-met-count targets ^{:line 717 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (employee-id e)))) 0 actives)]
  ^{:line 719 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} {:total-employees ^{:line 719 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (count employees) :active-employees ^{:line 719 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (count actives) :departments ^{:line 719 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (count ^{:line 719 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (unique-departments employees)) :total-commission total-comm :avg-commission ^{:line 719 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (if ^{:line 719 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (= ^{:line 719 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (count actives) 0) 0 ^{:line 719 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (quot total-comm ^{:line 719 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (count actives))) :avg-tenure ^{:line 719 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (avg-tenure-days employees now) :total-targets-met total-met :turnover-rate ^{:line 719 :file "/home/tom/code/beagle/experiments/v2-inventory/golden/beagle/employees.rkt"} (turnover-rate-pct employees)}))
