(when-not (= (r/count-words "hello world") 2) (System/exit 1))
(when-not (= (r/count-words "") 0) (System/exit 1))
(when-not (= (r/count-chars "hello") 5) (System/exit 1))
(when-not (= (r/longest-word "the quick brown fox") "quick") (System/exit 1))
(when-not (nil? (r/longest-word "")) (System/exit 1))
(let [s r/demo-result]
  (when-not (= (nth s 0) 9) (System/exit 1))
  (when-not (= (nth s 1) 43) (System/exit 1))
  (when-not (= (nth s 2) "quick") (System/exit 1)))
(System/exit 0)
