(when-not (= (r/header-level "# Intro") 1) (System/exit 1))
(when-not (= (r/header-level "## Sub") 2) (System/exit 1))
(when-not (= (r/header-level "### Deep") 3) (System/exit 1))
(when-not (= (r/header-text "# Introduction") "Introduction") (System/exit 1))
(when-not (= (r/header-text "## Background") "Background") (System/exit 1))
(when-not (r/header? "# test") (System/exit 1))
(when-not (not (r/header? "no header")) (System/exit 1))
(let [toc r/demo-result]
  (when-not (= (count toc) 5) (System/exit 1))
  (when-not (= (nth toc 0) "- Introduction") (System/exit 1))
  (when-not (= (nth toc 1) "  - Background") (System/exit 1))
  (when-not (= (nth toc 2) "  - Methods") (System/exit 1))
  (when-not (= (nth toc 3) "    - Data Collection") (System/exit 1))
  (when-not (= (nth toc 4) "- Conclusion") (System/exit 1)))
(System/exit 0)
