(when-not (= (r/letter-grade 95) "A") (System/exit 1))
(when-not (= (r/letter-grade 90) "A") (System/exit 1))
(when-not (= (r/letter-grade 85) "B") (System/exit 1))
(when-not (= (r/letter-grade 75) "C") (System/exit 1))
(when-not (= (r/letter-grade 65) "D") (System/exit 1))
(when-not (= (r/letter-grade 55) "F")
  (println "FAIL: (letter-grade 55) =>" (pr-str (r/letter-grade 55)))
  (System/exit 1))
(when-not (= (r/letter-grade 100) "A") (System/exit 1))
(System/exit 0)
