(when-not (= (r/fizzbuzz-of 15) "FizzBuzz")
  (println "FAIL: 15 =>" (pr-str (r/fizzbuzz-of 15)))
  (System/exit 1))
(when-not (= (r/fizzbuzz-of 9) "Fizz") (System/exit 1))
(when-not (= (r/fizzbuzz-of 25) "Buzz") (System/exit 1))
(when-not (= (r/fizzbuzz-of 7) "7")
  (println "FAIL: 7 =>" (pr-str (r/fizzbuzz-of 7)))
  (System/exit 1))
(when-not (= (r/fizzbuzz-of 30) "FizzBuzz") (System/exit 1))
(System/exit 0)
