(when-not (= (r/fib 0) 0)
  (println "FAIL: fib 0 =>" (pr-str (r/fib 0)))
  (System/exit 1))
(when-not (= (r/fib 1) 1) (System/exit 1))
(when-not (= (r/fib 2) 1) (System/exit 1))
(when-not (= (r/fib 10) 55)
  (println "FAIL: fib 10 =>" (pr-str (r/fib 10)))
  (System/exit 1))
(when-not (= (r/fib 15) 610) (System/exit 1))
(System/exit 0)
