(when-not (true?  (boolean (r/any-positive? [-1 0 5])))
  (println "FAIL: any-positive? [-1 0 5] =>" (pr-str (r/any-positive? [-1 0 5])))
  (System/exit 1))
(when-not (false? (boolean (r/any-positive? [-3 -2 -1])))
  (System/exit 1))
(when-not (false? (boolean (r/any-positive? [0 0 0]))) (System/exit 1))
(when-not (false? (boolean (r/any-positive? []))) (System/exit 1))
(when-not (true?  (boolean (r/any-positive? [42]))) (System/exit 1))
(System/exit 0)
