(ns inventory
  (:require [catalog :as cat]))

;; WarehouseId : Long (scalar)

^{:line 14 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (defrecord Warehouse [id name location capacity])

(defn warehouse-id [r] (:id r))

(defn warehouse-name [r] (:name r))

(defn warehouse-location [r] (:location r))

(defn warehouse-capacity [r] (:capacity r))

^{:line 17 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (defrecord StockLevel [warehouse-id product-id quantity min-quantity])

(defn stocklevel-warehouse-id [r] (:warehouse-id r))

(defn stocklevel-product-id [r] (:product-id r))

(defn stocklevel-quantity [r] (:quantity r))

(defn stocklevel-min-quantity [r] (:min-quantity r))

^{:line 20 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (defrecord StockMovement [id warehouse-id product-id quantity-change movement-type timestamp])

(defn stockmovement-id [r] (:id r))

(defn stockmovement-warehouse-id [r] (:warehouse-id r))

(defn stockmovement-product-id [r] (:product-id r))

(defn stockmovement-quantity-change [r] (:quantity-change r))

(defn stockmovement-movement-type [r] (:movement-type r))

(defn stockmovement-timestamp [r] (:timestamp r))

^{:line 26 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (defn find-warehouse-by-id [warehouses id]
  ^{:line 27 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (first ^{:line 27 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (filterv ^{:line 27 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (fn [w] ^{:line 27 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (= ^{:line 27 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (warehouse-id w) id)) warehouses)))

^{:line 29 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (defn warehouses-by-location [warehouses loc]
  ^{:line 30 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (filterv ^{:line 30 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (fn [w] ^{:line 30 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (= ^{:line 30 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (warehouse-location w) loc)) warehouses))

^{:line 32 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (defn sort-by-capacity [warehouses]
  ^{:line 33 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (sort-by warehouse-capacity warehouses))

^{:line 37 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (defn find-stock [levels wh-id prod-id]
  ^{:line 38 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (first ^{:line 38 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (filterv ^{:line 38 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (fn [s] ^{:line 38 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (and ^{:line 38 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (= ^{:line 38 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (stocklevel-warehouse-id s) wh-id) ^{:line 39 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (= ^{:line 39 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (stocklevel-product-id s) prod-id))) levels)))

^{:line 42 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (defn stock-for-product [levels prod-id]
  ^{:line 43 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (filterv ^{:line 43 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (fn [s] ^{:line 43 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (= ^{:line 43 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (stocklevel-product-id s) prod-id)) levels))

^{:line 45 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (defn stock-for-warehouse [levels wh-id]
  ^{:line 46 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (filterv ^{:line 46 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (fn [s] ^{:line 46 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (= ^{:line 46 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (stocklevel-warehouse-id s) wh-id)) levels))

^{:line 48 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (defn total-stock-for-product [levels prod-id]
  ^{:line 49 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (reduce ^{:line 49 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (fn [acc s] ^{:line 49 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (+ acc ^{:line 49 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (stocklevel-quantity s))) 0 ^{:line 51 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (stock-for-product levels prod-id)))

^{:line 53 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (defn total-stock-in-warehouse [levels wh-id]
  ^{:line 54 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (reduce ^{:line 54 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (fn [acc s] ^{:line 54 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (+ acc ^{:line 54 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (stocklevel-quantity s))) 0 ^{:line 56 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (stock-for-warehouse levels wh-id)))

^{:line 60 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (defn in-stock? [levels wh-id prod-id]
  ^{:line 61 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (let [sl ^{:line 61 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (find-stock levels wh-id prod-id)]
  ^{:line 62 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (if ^{:line 62 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (nil? sl) false ^{:line 62 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (> ^{:line 62 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (stocklevel-quantity sl) 0))))

^{:line 64 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (defn below-minimum? [sl]
  ^{:line 65 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (< ^{:line 65 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (stocklevel-quantity sl) ^{:line 65 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (stocklevel-min-quantity sl)))

^{:line 67 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (defn low-stock-items [levels]
  ^{:line 68 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (filterv below-minimum? levels))

^{:line 70 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (defn out-of-stock-items [levels]
  ^{:line 71 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (filterv ^{:line 71 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (fn [s] ^{:line 71 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (= ^{:line 71 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (stocklevel-quantity s) 0)) levels))

^{:line 73 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (defn available-quantity [levels prod-id]
  ^{:line 74 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (total-stock-for-product levels prod-id))

^{:line 76 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (defn can-fulfill? [levels prod-id qty]
  ^{:line 77 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (>= ^{:line 77 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (available-quantity levels prod-id) qty))

^{:line 81 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (defn stock-value-at-warehouse [levels wh-id products]
  ^{:line 82 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (let [wh-stock ^{:line 82 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (stock-for-warehouse levels wh-id)]
  ^{:line 83 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (reduce ^{:line 83 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (fn [acc sl] ^{:line 84 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (let [prod ^{:line 84 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (cat/find-product-by-id products ^{:line 84 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (stocklevel-product-id sl))
   cost ^{:line 85 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (if ^{:line 85 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (nil? prod) 0 ^{:line 85 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (cat/product-unit-cost prod))]
  ^{:line 86 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (+ acc ^{:line 86 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (* ^{:line 86 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (stocklevel-quantity sl) cost)))) 0 wh-stock)))

^{:line 89 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (defn stock-value-for-product [levels prod-id products]
  ^{:line 90 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (let [prod ^{:line 90 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (cat/find-product-by-id products prod-id)
   cost ^{:line 91 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (if ^{:line 91 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (nil? prod) 0 ^{:line 91 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (cat/product-unit-cost prod))
   qty ^{:line 92 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (total-stock-for-product levels prod-id)]
  ^{:line 93 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (* qty cost)))

^{:line 95 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (defn total-inventory-value [levels products]
  ^{:line 96 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (reduce ^{:line 96 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (fn [acc sl] ^{:line 97 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (let [prod ^{:line 97 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (cat/find-product-by-id products ^{:line 97 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (stocklevel-product-id sl))
   cost ^{:line 98 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (if ^{:line 98 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (nil? prod) 0 ^{:line 98 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (cat/product-unit-cost prod))]
  ^{:line 99 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (+ acc ^{:line 99 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (* ^{:line 99 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (stocklevel-quantity sl) cost)))) 0 levels))

^{:line 102 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (defn stock-retail-value [levels products]
  ^{:line 103 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (reduce ^{:line 103 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (fn [acc sl] ^{:line 104 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (let [prod ^{:line 104 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (cat/find-product-by-id products ^{:line 104 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (stocklevel-product-id sl))
   price ^{:line 105 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (if ^{:line 105 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (nil? prod) 0 ^{:line 105 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (cat/product-unit-price prod))]
  ^{:line 106 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (+ acc ^{:line 106 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (* ^{:line 106 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (stocklevel-quantity sl) price)))) 0 levels))

^{:line 111 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (defn reorder-needed [levels]
  ^{:line 112 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (filterv ^{:line 112 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (fn [sl] ^{:line 112 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (< ^{:line 112 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (stocklevel-quantity sl) ^{:line 112 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (stocklevel-min-quantity sl))) levels))

^{:line 115 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (defn reorder-quantity [sl]
  ^{:line 116 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (let [deficit ^{:line 116 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (- ^{:line 116 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (stocklevel-min-quantity sl) ^{:line 116 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (stocklevel-quantity sl))]
  ^{:line 117 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (if ^{:line 117 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (> deficit 0) ^{:line 117 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (* deficit 2) 0)))

^{:line 119 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (defn reorder-list [levels products]
  ^{:line 120 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (let [needed ^{:line 120 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (reorder-needed levels)]
  ^{:line 121 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (mapv ^{:line 121 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (fn [sl] ^{:line 122 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (let [prod ^{:line 122 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (cat/find-product-by-id products ^{:line 122 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (stocklevel-product-id sl))
   pname ^{:line 123 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (if ^{:line 123 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (nil? prod) "unknown" ^{:line 123 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (cat/product-name prod))
   qty ^{:line 124 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (reorder-quantity sl)]
  ^{:line 125 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} {:product-id ^{:line 125 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (stocklevel-product-id sl) :product-name pname :warehouse-id ^{:line 125 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (stocklevel-warehouse-id sl) :reorder-qty qty})) needed)))

^{:line 131 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (defn reorder-cost [levels products]
  ^{:line 132 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (let [needed ^{:line 132 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (reorder-needed levels)]
  ^{:line 133 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (reduce ^{:line 133 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (fn [acc sl] ^{:line 134 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (let [prod ^{:line 134 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (cat/find-product-by-id products ^{:line 134 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (stocklevel-product-id sl))
   cost ^{:line 135 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (if ^{:line 135 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (nil? prod) 0 ^{:line 135 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (cat/product-unit-cost prod))
   qty ^{:line 136 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (reorder-quantity sl)]
  ^{:line 137 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (+ acc ^{:line 137 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (* qty cost)))) 0 needed)))

^{:line 142 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (defn movements-for-product [movements prod-id]
  ^{:line 143 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (filterv ^{:line 143 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (fn [m] ^{:line 143 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (= ^{:line 143 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (stockmovement-product-id m) prod-id)) movements))

^{:line 145 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (defn movements-for-warehouse [movements wh-id]
  ^{:line 146 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (filterv ^{:line 146 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (fn [m] ^{:line 146 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (= ^{:line 146 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (stockmovement-warehouse-id m) wh-id)) movements))

^{:line 148 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (defn movements-by-type [movements mtype]
  ^{:line 149 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (filterv ^{:line 149 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (fn [m] ^{:line 149 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (= ^{:line 149 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (stockmovement-movement-type m) mtype)) movements))

^{:line 151 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (defn net-movement [movements prod-id]
  ^{:line 152 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (reduce ^{:line 152 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (fn [acc m] ^{:line 152 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (+ acc ^{:line 152 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (stockmovement-quantity-change m))) 0 ^{:line 154 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (movements-for-product movements prod-id)))

^{:line 156 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (defn total-received [movements prod-id]
  ^{:line 157 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (reduce ^{:line 157 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (fn [acc m] ^{:line 157 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (+ acc ^{:line 157 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (stockmovement-quantity-change m))) 0 ^{:line 159 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (filterv ^{:line 159 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (fn [m] ^{:line 159 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (and ^{:line 159 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (= ^{:line 159 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (stockmovement-product-id m) prod-id) ^{:line 160 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (= ^{:line 160 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (stockmovement-movement-type m) "receive"))) movements)))

^{:line 163 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (defn total-shipped [movements prod-id]
  ^{:line 164 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (reduce ^{:line 164 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (fn [acc m] ^{:line 164 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (+ acc ^{:line 164 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (- 0 ^{:line 164 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (stockmovement-quantity-change m)))) 0 ^{:line 166 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (filterv ^{:line 166 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (fn [m] ^{:line 166 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (and ^{:line 166 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (= ^{:line 166 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (stockmovement-product-id m) prod-id) ^{:line 167 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (= ^{:line 167 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (stockmovement-movement-type m) "ship"))) movements)))

^{:line 172 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (defn apply-movement [levels mv]
  ^{:line 173 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (let [wh-id ^{:line 173 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (stockmovement-warehouse-id mv)
   prod-id ^{:line 174 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (stockmovement-product-id mv)
   change ^{:line 175 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (stockmovement-quantity-change mv)]
  ^{:line 176 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (mapv ^{:line 176 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (fn [sl] ^{:line 177 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (if ^{:line 177 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (and ^{:line 177 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (= ^{:line 177 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (stocklevel-warehouse-id sl) wh-id) ^{:line 178 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (= ^{:line 178 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (stocklevel-product-id sl) prod-id)) ^{:line 179 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (->StockLevel wh-id prod-id ^{:line 180 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (+ ^{:line 180 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (stocklevel-quantity sl) change) ^{:line 181 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (stocklevel-min-quantity sl)) sl)) levels)))

^{:line 185 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (defn apply-movements [levels movements]
  ^{:line 186 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (reduce apply-movement levels movements))

^{:line 190 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (defn warehouse-item-count [levels wh-id]
  ^{:line 191 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (count ^{:line 191 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (stock-for-warehouse levels wh-id)))

^{:line 193 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (defn warehouse-total-units [levels wh-id]
  ^{:line 194 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (total-stock-in-warehouse levels wh-id))

^{:line 196 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (defn warehouse-utilization-pct [levels wh]
  ^{:line 197 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (let [total ^{:line 197 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (warehouse-total-units levels ^{:line 197 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (warehouse-id wh))
   cap ^{:line 198 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (warehouse-capacity wh)]
  ^{:line 199 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (if ^{:line 199 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (= cap 0) 0 ^{:line 199 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (quot ^{:line 199 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (* total 100) cap))))

^{:line 203 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (defn stock-summary [sl]
  ^{:line 204 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (str "WH:" ^{:line 204 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (stocklevel-warehouse-id sl) " Prod:" ^{:line 205 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (stocklevel-product-id sl) " Qty:" ^{:line 206 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (stocklevel-quantity sl) "/" ^{:line 207 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (stocklevel-min-quantity sl)))

^{:line 209 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (defn warehouse-summary [wh]
  ^{:line 210 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (str ^{:line 210 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (warehouse-name wh) " (" ^{:line 210 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (warehouse-location wh) ") cap:" ^{:line 211 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (warehouse-capacity wh)))

^{:line 215 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (defn stock-with-product-names [levels products]
  ^{:line 216 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (mapv ^{:line 216 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (fn [sl] ^{:line 217 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (let [prod ^{:line 217 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (cat/find-product-by-id products ^{:line 217 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (stocklevel-product-id sl))
   pname ^{:line 218 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (if ^{:line 218 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (nil? prod) "unknown" ^{:line 218 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (cat/product-name prod))]
  ^{:line 219 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} {:product-name pname :warehouse-id ^{:line 219 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (stocklevel-warehouse-id sl) :quantity ^{:line 219 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (stocklevel-quantity sl) :min-quantity ^{:line 219 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (stocklevel-min-quantity sl)})) levels))

^{:line 225 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (defn products-out-of-stock [levels products]
  ^{:line 226 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (let [oos-ids ^{:line 226 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (mapv ^{:line 226 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (fn [sl] ^{:line 226 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (stocklevel-product-id sl)) ^{:line 226 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (out-of-stock-items levels))]
  ^{:line 227 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (filterv ^{:line 227 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (fn [p] ^{:line 227 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (some ^{:line 227 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (fn [id] ^{:line 227 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (= ^{:line 227 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (cat/product-id p) id)) oos-ids)) products)))

^{:line 232 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (defrecord Transfer [id from-warehouse to-warehouse product-id quantity timestamp])

(defn transfer-id [r] (:id r))

(defn transfer-from-warehouse [r] (:from-warehouse r))

(defn transfer-to-warehouse [r] (:to-warehouse r))

(defn transfer-product-id [r] (:product-id r))

(defn transfer-quantity [r] (:quantity r))

(defn transfer-timestamp [r] (:timestamp r))

^{:line 235 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (defn create-transfer [id from-wh to-wh prod-id qty ts]
  ^{:line 237 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (->Transfer id from-wh to-wh prod-id qty ts))

^{:line 239 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (defn can-transfer? [levels from-wh prod-id qty]
  ^{:line 240 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (let [sl ^{:line 240 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (find-stock levels from-wh prod-id)]
  ^{:line 241 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (if ^{:line 241 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (nil? sl) false ^{:line 241 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (>= ^{:line 241 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (stocklevel-quantity sl) qty))))

^{:line 243 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (defn apply-transfer [levels tr]
  ^{:line 244 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (let [from-wh ^{:line 244 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (transfer-from-warehouse tr)
   to-wh ^{:line 245 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (transfer-to-warehouse tr)
   prod-id ^{:line 246 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (transfer-product-id tr)
   qty ^{:line 247 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (transfer-quantity tr)]
  ^{:line 248 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (mapv ^{:line 248 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (fn [sl] ^{:line 249 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (cond
  ^{:line 250 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (and ^{:line 250 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (= ^{:line 250 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (stocklevel-warehouse-id sl) from-wh) ^{:line 251 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (= ^{:line 251 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (stocklevel-product-id sl) prod-id)) ^{:line 252 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (->StockLevel from-wh prod-id ^{:line 253 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (- ^{:line 253 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (stocklevel-quantity sl) qty) ^{:line 254 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (stocklevel-min-quantity sl))
  ^{:line 255 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (and ^{:line 255 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (= ^{:line 255 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (stocklevel-warehouse-id sl) to-wh) ^{:line 256 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (= ^{:line 256 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (stocklevel-product-id sl) prod-id)) ^{:line 257 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (->StockLevel to-wh prod-id ^{:line 258 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (+ ^{:line 258 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (stocklevel-quantity sl) qty) ^{:line 259 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (stocklevel-min-quantity sl))
  true sl)) levels)))

^{:line 263 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (defn transfers-for-product [transfers prod-id]
  ^{:line 264 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (filterv ^{:line 264 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (fn [t] ^{:line 264 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (= ^{:line 264 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (transfer-product-id t) prod-id)) transfers))

^{:line 266 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (defn transfers-from-warehouse [transfers wh-id]
  ^{:line 267 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (filterv ^{:line 267 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (fn [t] ^{:line 267 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (= ^{:line 267 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (transfer-from-warehouse t) wh-id)) transfers))

^{:line 269 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (defn transfers-to-warehouse [transfers wh-id]
  ^{:line 270 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (filterv ^{:line 270 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (fn [t] ^{:line 270 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (= ^{:line 270 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (transfer-to-warehouse t) wh-id)) transfers))

^{:line 274 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (defn product-stock-value [levels prod-id products]
  ^{:line 275 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (stock-value-for-product levels prod-id products))

^{:line 277 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (defn classify-abc [value total-value]
  ^{:line 278 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (let [pct ^{:line 278 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (if ^{:line 278 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (= total-value 0) 0 ^{:line 278 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (quot ^{:line 278 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (* value 100) total-value))]
  ^{:line 279 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (cond
  ^{:line 280 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (>= pct 20) "A"
  ^{:line 281 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (>= pct 5) "B"
  true "C")))

^{:line 284 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (defn abc-analysis [levels products]
  ^{:line 285 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (let [total ^{:line 285 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (total-inventory-value levels products)]
  ^{:line 286 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (mapv ^{:line 286 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (fn [p] ^{:line 287 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (let [pid ^{:line 287 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (cat/product-id p)
   value ^{:line 288 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (product-stock-value levels pid products)
   class ^{:line 289 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (classify-abc value total)]
  ^{:line 290 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} {:product-id pid :product-name ^{:line 290 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (cat/product-name p) :stock-value value :abc-class class})) products)))

^{:line 298 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (defn safety-stock [avg-daily-demand lead-time-days safety-factor]
  ^{:line 300 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (* avg-daily-demand lead-time-days safety-factor))

^{:line 302 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (defn recommended-min-quantity [avg-daily-demand supplier safety-factor]
  ^{:line 304 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (let [lead-time ^{:line 304 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (if ^{:line 304 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (nil? supplier) 7 ^{:line 304 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (cat/supplier-lead-time-days supplier))]
  ^{:line 305 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (safety-stock avg-daily-demand lead-time safety-factor)))

^{:line 309 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (defn batch-receive [levels wh-id items]
  ^{:line 310 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (reduce ^{:line 310 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (fn [lvls item] ^{:line 311 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (let [prod-id ^{:line 311 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (first item)
   qty ^{:line 312 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (second item)]
  ^{:line 313 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (mapv ^{:line 313 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (fn [sl] ^{:line 314 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (if ^{:line 314 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (and ^{:line 314 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (= ^{:line 314 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (stocklevel-warehouse-id sl) wh-id) ^{:line 315 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (= ^{:line 315 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (stocklevel-product-id sl) prod-id)) ^{:line 316 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (->StockLevel wh-id prod-id ^{:line 317 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (+ ^{:line 317 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (stocklevel-quantity sl) qty) ^{:line 318 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (stocklevel-min-quantity sl)) sl)) lvls))) levels items))

^{:line 323 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (defn batch-ship [levels wh-id items]
  ^{:line 324 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (reduce ^{:line 324 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (fn [lvls item] ^{:line 325 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (let [prod-id ^{:line 325 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (first item)
   qty ^{:line 326 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (second item)]
  ^{:line 327 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (mapv ^{:line 327 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (fn [sl] ^{:line 328 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (if ^{:line 328 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (and ^{:line 328 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (= ^{:line 328 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (stocklevel-warehouse-id sl) wh-id) ^{:line 329 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (= ^{:line 329 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (stocklevel-product-id sl) prod-id)) ^{:line 330 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (->StockLevel wh-id prod-id ^{:line 331 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (- ^{:line 331 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (stocklevel-quantity sl) qty) ^{:line 332 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (stocklevel-min-quantity sl)) sl)) lvls))) levels items))

^{:line 339 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (defn days-of-stock [levels prod-id daily-demand]
  ^{:line 340 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (let [qty ^{:line 340 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (total-stock-for-product levels prod-id)]
  ^{:line 341 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (if ^{:line 341 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (= daily-demand 0) 999 ^{:line 341 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (quot qty daily-demand))))

^{:line 343 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (defn overstocked-products [levels products max-days daily-demands]
  ^{:line 345 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (filterv ^{:line 345 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (fn [p] ^{:line 346 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (let [pid ^{:line 346 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (cat/product-id p)
   raw ^{:line 347 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (get daily-demands pid)
   demand ^{:line 348 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (if ^{:line 348 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (nil? raw) 1 raw)]
  ^{:line 349 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (> ^{:line 349 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run3/inventory.rkt"} (days-of-stock levels pid demand) max-days))) products))
