(ns audit
  (:require [catalog :as cat]
            [customers :as cust]
            [inventory :as inv]
            [orders :as ord]
            [shipping :as ship]
            [billing :as bill]
            [procurement :as proc]
            [promotions :as promo]
            [employees :as emp]
            [notifications :as notif]))

^{:line 21 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (defrecord AuditEntry [id entity-type entity-id action actor-id timestamp detail])

(defn auditentry-id [r] (:id r))

(defn auditentry-entity-type [r] (:entity-type r))

(defn auditentry-entity-id [r] (:entity-id r))

(defn auditentry-action [r] (:action r))

(defn auditentry-actor-id [r] (:actor-id r))

(defn auditentry-timestamp [r] (:timestamp r))

(defn auditentry-detail [r] (:detail r))

^{:line 25 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (defrecord ReconciliationResult [period expected actual discrepancy status])

(defn reconciliationresult-period [r] (:period r))

(defn reconciliationresult-expected [r] (:expected r))

(defn reconciliationresult-actual [r] (:actual r))

(defn reconciliationresult-discrepancy [r] (:discrepancy r))

(defn reconciliationresult-status [r] (:status r))

^{:line 29 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (defrecord ComplianceCheck [id check-type entity-id passed detail checked-at])

(defn compliancecheck-id [r] (:id r))

(defn compliancecheck-check-type [r] (:check-type r))

(defn compliancecheck-entity-id [r] (:entity-id r))

(defn compliancecheck-passed [r] (:passed r))

(defn compliancecheck-detail [r] (:detail r))

(defn compliancecheck-checked-at [r] (:checked-at r))

^{:line 38 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (defn create-audit-entry [id entity-type entity-id action actor-id timestamp detail]
  ^{:line 42 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (->AuditEntry id entity-type entity-id action actor-id timestamp detail))

^{:line 46 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (defn audit-order [id order actor-id action timestamp]
  ^{:line 48 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (->AuditEntry id "order" ^{:line 48 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (ord/order-id order) action actor-id timestamp ^{:line 49 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (ord/order-status order)))

^{:line 53 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (defn audit-shipment [id shipment actor-id action timestamp]
  ^{:line 55 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (->AuditEntry id "shipment" ^{:line 55 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (ship/shipment-id shipment) action actor-id timestamp ^{:line 56 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (ship/shipment-status shipment)))

^{:line 60 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (defn audit-invoice [id invoice actor-id action timestamp]
  ^{:line 62 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (->AuditEntry id "invoice" ^{:line 62 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (bill/invoice-id invoice) action actor-id timestamp ^{:line 63 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (bill/invoice-status invoice)))

^{:line 67 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (defn audit-product [id product actor-id action timestamp]
  ^{:line 69 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (->AuditEntry id "product" ^{:line 69 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (cat/product-id product) action actor-id timestamp ^{:line 70 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (cat/product-name product)))

^{:line 77 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (defn entries-for-entity [entries entity-type entity-id]
  ^{:line 79 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (filterv ^{:line 79 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (fn [e] ^{:line 79 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (and ^{:line 79 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (= ^{:line 79 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (auditentry-entity-type e) entity-type) ^{:line 80 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (= ^{:line 80 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (auditentry-entity-id e) entity-id))) entries))

^{:line 84 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (defn entries-by-actor [entries actor-id]
  ^{:line 85 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (filterv ^{:line 85 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (fn [e] ^{:line 85 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (= ^{:line 85 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (auditentry-actor-id e) actor-id)) entries))

^{:line 90 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (defn entries-by-action [entries action]
  ^{:line 91 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (filterv ^{:line 91 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (fn [e] ^{:line 91 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (= ^{:line 91 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (auditentry-action e) action)) entries))

^{:line 94 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (defn entries-in-period [entries start end]
  ^{:line 96 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (filterv ^{:line 96 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (fn [e] ^{:line 96 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (and ^{:line 96 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (>= ^{:line 96 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (auditentry-timestamp e) start) ^{:line 98 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (<= ^{:line 98 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (auditentry-timestamp e) end))) entries))

^{:line 103 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (defn entry-count-by-type [entries entity-type]
  ^{:line 104 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (count ^{:line 104 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (filterv ^{:line 104 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (fn [e] ^{:line 104 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (= ^{:line 104 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (auditentry-entity-type e) entity-type)) entries)))

^{:line 108 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (defn recent-entries [entries n]
  ^{:line 109 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (let [sorted ^{:line 109 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (reverse ^{:line 109 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (sort-by ^{:line 109 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (fn [e] ^{:line 109 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (auditentry-timestamp e)) entries))]
  ^{:line 111 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (vec ^{:line 111 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (take n sorted))))

^{:line 114 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (defn actor-action-count [entries actor-id]
  ^{:line 115 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (count ^{:line 115 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (entries-by-actor entries actor-id)))

^{:line 122 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (defn entries-by-entity-type [entries entity-type]
  ^{:line 123 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (filterv ^{:line 123 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (fn [e] ^{:line 123 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (= ^{:line 123 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (auditentry-entity-type e) entity-type)) entries))

^{:line 126 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (defn distinct-actors [entries]
  ^{:line 127 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (distinct ^{:line 127 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (mapv auditentry-actor-id entries)))

^{:line 130 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (defn distinct-entity-types [entries]
  ^{:line 131 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (distinct ^{:line 131 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (mapv auditentry-entity-type entries)))

^{:line 134 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (defn entries-for-actor-in-period [entries actor-id start end]
  ^{:line 137 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (filterv ^{:line 137 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (fn [e] ^{:line 137 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (and ^{:line 137 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (= ^{:line 137 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (auditentry-actor-id e) actor-id) ^{:line 139 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (>= ^{:line 139 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (auditentry-timestamp e) start) ^{:line 141 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (<= ^{:line 141 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (auditentry-timestamp e) end))) entries))

^{:line 146 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (defn actor-most-recent-entry [entries actor-id]
  ^{:line 147 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (let [actor-entries ^{:line 147 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (entries-by-actor entries actor-id)]
  ^{:line 148 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (if ^{:line 148 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (empty? actor-entries) nil ^{:line 150 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (let [sorted ^{:line 150 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (reverse ^{:line 150 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (sort-by ^{:line 150 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (fn [e] ^{:line 150 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (auditentry-timestamp e)) actor-entries))]
  ^{:line 152 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (first sorted)))))

^{:line 159 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (defn audit-entry-summary [e]
  ^{:line 160 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (str "Audit #" ^{:line 160 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (auditentry-id e) " | " ^{:line 161 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (auditentry-entity-type e) " #" ^{:line 161 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (auditentry-entity-id e) " | " ^{:line 162 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (auditentry-action e) " | Actor: " ^{:line 163 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (auditentry-actor-id e) " | " ^{:line 164 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (auditentry-detail e)))

^{:line 167 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (defn audit-entry-detail [e]
  ^{:line 168 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (str "Audit #" ^{:line 168 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (auditentry-id e) " | Entity: " ^{:line 169 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (auditentry-entity-type e) " #" ^{:line 169 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (auditentry-entity-id e) " | Action: " ^{:line 170 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (auditentry-action e) " | Actor: " ^{:line 171 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (auditentry-actor-id e) " | Timestamp: " ^{:line 172 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (auditentry-timestamp e) " | Detail: " ^{:line 173 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (auditentry-detail e)))

^{:line 180 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (defn valid-audit-entry? [e]
  ^{:line 181 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (and ^{:line 181 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (> ^{:line 181 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (auditentry-id e) 0) ^{:line 182 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (not= ^{:line 182 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (auditentry-entity-type e) "") ^{:line 183 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (> ^{:line 183 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (auditentry-entity-id e) 0) ^{:line 184 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (not= ^{:line 184 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (auditentry-action e) "") ^{:line 185 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (> ^{:line 185 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (auditentry-actor-id e) 0) ^{:line 186 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (> ^{:line 186 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (auditentry-timestamp e) 0)))

^{:line 193 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (defn audit-entry-count [entries]
  ^{:line 194 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (count entries))

^{:line 197 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (defn action-distribution [entries]
  ^{:line 198 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (let [creates ^{:line 198 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (count ^{:line 198 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (entries-by-action entries "create"))
   updates ^{:line 199 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (count ^{:line 199 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (entries-by-action entries "update"))
   cancels ^{:line 200 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (count ^{:line 200 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (entries-by-action entries "cancel"))
   deletes ^{:line 201 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (count ^{:line 201 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (entries-by-action entries "delete"))]
  ^{:line 202 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} {:create creates :update updates :cancel cancels :delete deletes}))

^{:line 205 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (defn entity-type-distribution [entries]
  ^{:line 206 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (let [orders-cnt ^{:line 206 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (entry-count-by-type entries "order")
   shipments-cnt ^{:line 207 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (entry-count-by-type entries "shipment")
   invoices-cnt ^{:line 208 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (entry-count-by-type entries "invoice")
   products-cnt ^{:line 209 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (entry-count-by-type entries "product")]
  ^{:line 210 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} {:order orders-cnt :shipment shipments-cnt :invoice invoices-cnt :product products-cnt}))

^{:line 214 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (defn actor-activity-summary [entries]
  ^{:line 215 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (let [actors ^{:line 215 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (distinct-actors entries)]
  ^{:line 216 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (mapv ^{:line 216 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (fn [aid] ^{:line 217 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} {:actor-id aid :entry-count ^{:line 217 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (actor-action-count entries aid)}) actors)))

^{:line 222 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (defn most-active-actor [entries]
  ^{:line 223 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (let [actors ^{:line 223 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (distinct-actors entries)]
  ^{:line 224 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (if ^{:line 224 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (empty? actors) 0 ^{:line 226 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (reduce ^{:line 226 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (fn [best aid] ^{:line 227 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (if ^{:line 227 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (> ^{:line 227 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (actor-action-count entries aid) ^{:line 228 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (actor-action-count entries best)) aid best)) ^{:line 231 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (first actors) ^{:line 232 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (rest actors)))))

^{:line 235 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (defn entries-per-day [entries start end]
  ^{:line 237 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (let [period-entries ^{:line 237 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (entries-in-period entries start end)
   days ^{:line 238 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (quot ^{:line 238 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (- end start) 86400)]
  ^{:line 239 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (if ^{:line 239 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (<= days 0) ^{:line 239 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (count period-entries) ^{:line 240 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (quot ^{:line 240 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (count period-entries) days))))

^{:line 253 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (defn reconcile-revenue [orders invoices period-start period-end]
  ^{:line 256 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (let [period-orders ^{:line 256 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (ord/orders-in-period orders period-start period-end)
   expected ^{:line 257 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (ord/total-revenue period-orders)
   period-invoices ^{:line 258 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (filterv ^{:line 258 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (fn [inv] ^{:line 259 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (and ^{:line 259 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (>= ^{:line 259 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (bill/invoice-issued-at inv) period-start) ^{:line 261 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (<= ^{:line 261 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (bill/invoice-issued-at inv) period-end))) invoices)
   actual ^{:line 264 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (reduce ^{:line 264 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (fn [acc inv] ^{:line 264 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (+ acc ^{:line 264 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (bill/invoice-total inv))) 0 period-invoices)
   disc ^{:line 266 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (- expected actual)
   status ^{:line 267 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (if ^{:line 267 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (= disc 0) "balanced" "discrepancy")
   period-label ^{:line 268 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (str period-start "-" period-end)]
  ^{:line 270 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (->ReconciliationResult period-label expected actual disc status)))

^{:line 278 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (defn reconcile-inventory [levels products movements]
  ^{:line 280 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (let [expected ^{:line 280 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (inv/total-inventory-value levels products)
   actual ^{:line 281 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (reduce ^{:line 281 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (fn [acc m] ^{:line 282 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (let [prod ^{:line 282 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (cat/find-product-by-id products ^{:line 284 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (inv/stockmovement-product-id m))
   cost ^{:line 285 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (if ^{:line 285 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (nil? prod) 0 ^{:line 285 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (cat/product-unit-cost prod))
   qty ^{:line 286 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (inv/stockmovement-quantity-change m)]
  ^{:line 287 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (+ acc ^{:line 287 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (* qty cost)))) 0 movements)
   disc ^{:line 289 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (- expected actual)
   status ^{:line 290 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (if ^{:line 290 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (= disc 0) "balanced" "discrepancy")]
  ^{:line 291 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (->ReconciliationResult "current" expected actual disc status)))

^{:line 294 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (defn reconciliation-healthy? [result]
  ^{:line 295 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (= ^{:line 295 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (reconciliationresult-status result) "balanced"))

^{:line 302 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (defn reconcile-billing-payments [invoices payments]
  ^{:line 304 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (let [total-billed ^{:line 304 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (reduce ^{:line 304 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (fn [acc inv] ^{:line 304 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (+ acc ^{:line 304 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (bill/invoice-total inv))) 0 invoices)
   total-collected ^{:line 306 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (bill/total-revenue-collected payments)
   disc ^{:line 307 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (- total-billed total-collected)
   status ^{:line 308 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (if ^{:line 308 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (= disc 0) "balanced" "discrepancy")]
  ^{:line 309 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (->ReconciliationResult "billing" total-billed total-collected disc status)))

^{:line 314 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (defn reconcile-shipping-orders [orders shipments]
  ^{:line 316 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (let [active ^{:line 316 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (ord/active-orders orders)
   expected ^{:line 317 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (count active)
   shipped ^{:line 318 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (count ^{:line 318 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (ship/orders-with-shipments shipments active))
   disc ^{:line 319 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (- expected shipped)
   status ^{:line 320 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (if ^{:line 320 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (= disc 0) "balanced" "discrepancy")]
  ^{:line 321 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (->ReconciliationResult "shipping-coverage" ^{:line 322 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (long expected) ^{:line 323 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (long shipped) ^{:line 324 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (long disc) status)))

^{:line 330 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (defn reconcile-procurement-inventory [pos levels products]
  ^{:line 332 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (let [expected ^{:line 332 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (proc/total-procurement-spend pos)
   actual ^{:line 333 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (inv/total-inventory-value levels products)
   disc ^{:line 334 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (- expected actual)
   status ^{:line 335 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (if ^{:line 335 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (= disc 0) "balanced" "discrepancy")]
  ^{:line 336 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (->ReconciliationResult "procurement-inventory" expected actual disc status)))

^{:line 339 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (defn reconciliation-result-summary [r]
  ^{:line 340 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (str "Period: " ^{:line 340 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (reconciliationresult-period r) " | Expected: " ^{:line 341 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (reconciliationresult-expected r) " | Actual: " ^{:line 342 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (reconciliationresult-actual r) " | Discrepancy: " ^{:line 343 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (reconciliationresult-discrepancy r) " | Status: " ^{:line 344 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (reconciliationresult-status r)))

^{:line 347 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (defn discrepancy-pct [result]
  ^{:line 348 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (let [exp ^{:line 348 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (reconciliationresult-expected result)]
  ^{:line 349 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (if ^{:line 349 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (= exp 0) 0 ^{:line 350 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (let [disc ^{:line 350 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (reconciliationresult-discrepancy result)
   abs-disc ^{:line 351 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (if ^{:line 351 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (< disc 0) ^{:line 351 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (- 0 disc) disc)]
  ^{:line 352 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (quot ^{:line 352 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (* abs-disc 100) exp)))))

^{:line 360 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (defn check-order-has-customer [order customers]
  ^{:line 361 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (let [cust-id ^{:line 361 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (ord/order-customer-id order)
   customer ^{:line 362 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (cust/find-customer-by-id customers cust-id)
   passed ^{:line 363 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (not ^{:line 363 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (nil? customer))
   detail ^{:line 364 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (if passed ^{:line 365 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (str "Customer #" cust-id " exists") ^{:line 366 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (str "Customer #" cust-id " not found"))]
  ^{:line 367 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (->ComplianceCheck 0 "order-has-customer" ^{:line 367 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (ord/order-id order) passed detail 0)))

^{:line 372 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (defn check-invoice-matches-order [invoice orders]
  ^{:line 374 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (let [order ^{:line 374 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (ord/find-order-by-id orders ^{:line 374 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (bill/invoice-order-id invoice))
   passed ^{:line 375 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (if ^{:line 375 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (nil? order) false ^{:line 377 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (= ^{:line 377 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (bill/invoice-total invoice) ^{:line 378 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (ord/order-total order)))
   detail ^{:line 379 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (if ^{:line 379 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (nil? order) ^{:line 380 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (str "Order #" ^{:line 380 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (bill/invoice-order-id invoice) " not found") ^{:line 382 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (if passed ^{:line 383 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (str "Invoice total matches order total: " ^{:line 384 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (bill/invoice-total invoice)) ^{:line 385 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (str "Invoice total " ^{:line 386 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (bill/invoice-total invoice) " != order total " ^{:line 388 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (ord/order-total order))))]
  ^{:line 389 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (->ComplianceCheck 0 "invoice-matches-order" ^{:line 390 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (bill/invoice-id invoice) passed detail 0)))

^{:line 394 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (defn check-shipment-has-order [shipment orders]
  ^{:line 396 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (let [order-id ^{:line 396 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (ship/shipment-order-id shipment)
   order ^{:line 397 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (ord/find-order-by-id orders order-id)
   passed ^{:line 398 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (not ^{:line 398 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (nil? order))
   detail ^{:line 399 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (if passed ^{:line 400 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (str "Order #" order-id " exists") ^{:line 401 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (str "Order #" order-id " not found"))]
  ^{:line 402 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (->ComplianceCheck 0 "shipment-has-order" ^{:line 403 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (ship/shipment-id shipment) passed detail 0)))

^{:line 407 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (defn check-payment-within-invoice [payment invoices]
  ^{:line 409 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (let [inv ^{:line 409 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (bill/find-invoice-by-id invoices ^{:line 409 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (bill/payment-invoice-id payment))
   passed ^{:line 410 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (if ^{:line 410 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (nil? inv) false ^{:line 412 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (<= ^{:line 412 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (bill/payment-amount payment) ^{:line 413 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (bill/invoice-total inv)))
   detail ^{:line 414 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (if ^{:line 414 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (nil? inv) ^{:line 415 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (str "Invoice #" ^{:line 415 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (bill/payment-invoice-id payment) " not found") ^{:line 417 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (if passed ^{:line 418 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (str "Payment " ^{:line 418 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (bill/payment-amount payment) " <= invoice total " ^{:line 420 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (bill/invoice-total inv)) ^{:line 421 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (str "Payment " ^{:line 421 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (bill/payment-amount payment) " > invoice total " ^{:line 423 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (bill/invoice-total inv))))]
  ^{:line 424 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (->ComplianceCheck 0 "payment-within-invoice" ^{:line 425 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (bill/payment-id payment) passed detail 0)))

^{:line 433 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (defn check-employee-exists [actor-id employees]
  ^{:line 435 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (let [employee ^{:line 435 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (emp/find-employee-by-id employees actor-id)
   passed ^{:line 436 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (not ^{:line 436 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (nil? employee))
   detail ^{:line 437 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (if passed ^{:line 438 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (str "Employee #" actor-id " exists: " ^{:line 439 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (emp/employee-name employee)) ^{:line 440 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (str "Employee #" actor-id " not found"))]
  ^{:line 441 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (->ComplianceCheck 0 "employee-exists" actor-id passed detail 0)))

^{:line 445 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (defn check-product-active [product]
  ^{:line 446 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (let [passed ^{:line 446 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (cat/product-active product)
   detail ^{:line 447 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (if passed ^{:line 448 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (str "Product #" ^{:line 448 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (cat/product-id product) " is active") ^{:line 450 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (str "Product #" ^{:line 450 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (cat/product-id product) " is inactive"))]
  ^{:line 452 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (->ComplianceCheck 0 "product-active" ^{:line 452 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (cat/product-id product) passed detail 0)))

^{:line 456 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (defn check-invoice-not-overdue [invoice now]
  ^{:line 458 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (let [is-overdue ^{:line 458 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (and ^{:line 458 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (= ^{:line 458 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (bill/invoice-status invoice) "unpaid") ^{:line 459 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (< ^{:line 459 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (bill/invoice-due-at invoice) now))
   passed ^{:line 461 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (not is-overdue)
   detail ^{:line 462 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (if passed ^{:line 463 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (str "Invoice #" ^{:line 463 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (bill/invoice-id invoice) " is current") ^{:line 465 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (str "Invoice #" ^{:line 465 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (bill/invoice-id invoice) " is overdue"))]
  ^{:line 467 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (->ComplianceCheck 0 "invoice-not-overdue" ^{:line 468 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (bill/invoice-id invoice) passed detail now)))

^{:line 472 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (defn check-po-within-budget [po budget-limit]
  ^{:line 474 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (let [po-total ^{:line 474 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (proc/purchaseorder-total po)
   passed ^{:line 475 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (<= po-total budget-limit)
   detail ^{:line 476 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (if passed ^{:line 477 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (str "PO #" ^{:line 477 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (proc/purchaseorder-id po) " total " po-total " within budget " budget-limit) ^{:line 479 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (str "PO #" ^{:line 479 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (proc/purchaseorder-id po) " total " po-total " exceeds budget " budget-limit))]
  ^{:line 481 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (->ComplianceCheck 0 "po-within-budget" ^{:line 482 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (proc/purchaseorder-id po) passed detail 0)))

^{:line 490 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (defn run-order-checks [orders customers]
  ^{:line 491 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (mapv ^{:line 491 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (fn [o] ^{:line 491 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (check-order-has-customer o customers)) orders))

^{:line 494 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (defn run-invoice-checks [invoices orders]
  ^{:line 495 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (mapv ^{:line 495 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (fn [inv] ^{:line 495 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (check-invoice-matches-order inv orders)) invoices))

^{:line 498 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (defn run-shipment-checks [shipments orders]
  ^{:line 499 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (mapv ^{:line 499 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (fn [s] ^{:line 499 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (check-shipment-has-order s orders)) shipments))

^{:line 502 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (defn run-payment-checks [payments invoices]
  ^{:line 503 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (mapv ^{:line 503 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (fn [p] ^{:line 503 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (check-payment-within-invoice p invoices)) payments))

^{:line 506 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (defn compliance-pass-rate [checks]
  ^{:line 507 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (let [total ^{:line 507 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (count checks)]
  ^{:line 508 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (if ^{:line 508 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (= total 0) 100 ^{:line 509 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (let [passed-count ^{:line 509 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (count ^{:line 509 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (filterv ^{:line 509 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (fn [c] ^{:line 510 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (compliancecheck-passed c)) checks))]
  ^{:line 512 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (quot ^{:line 512 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (* passed-count 100) total)))))

^{:line 515 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (defn failed-checks [checks]
  ^{:line 516 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (filterv ^{:line 516 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (fn [c] ^{:line 516 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (not ^{:line 516 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (compliancecheck-passed c))) checks))

^{:line 520 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (defn passed-checks [checks]
  ^{:line 521 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (filterv ^{:line 521 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (fn [c] ^{:line 521 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (compliancecheck-passed c)) checks))

^{:line 526 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (defn compliance-summary [order-checks invoice-checks shipment-checks]
  ^{:line 528 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (let [all-checks ^{:line 528 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (into ^{:line 528 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} [] ^{:line 528 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (concat order-checks invoice-checks shipment-checks))
   total ^{:line 529 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (count all-checks)
   passed-cnt ^{:line 530 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (count ^{:line 530 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (passed-checks all-checks))
   failed-cnt ^{:line 531 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (count ^{:line 531 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (failed-checks all-checks))
   rate ^{:line 532 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (compliance-pass-rate all-checks)]
  ^{:line 533 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} {:total-checks total :passed passed-cnt :failed failed-cnt :pass-rate rate}))

^{:line 543 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (defn compliance-check-summary [c]
  ^{:line 544 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (str "Check #" ^{:line 544 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (compliancecheck-id c) " | " ^{:line 545 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (compliancecheck-check-type c) " | Entity: " ^{:line 546 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (compliancecheck-entity-id c) " | " ^{:line 547 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (if ^{:line 547 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (compliancecheck-passed c) "PASSED" "FAILED") " | " ^{:line 548 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (compliancecheck-detail c)))

^{:line 555 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (defn audit-order-lifecycle [base-id order actor-id timestamp]
  ^{:line 558 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (let [oid ^{:line 558 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (ord/order-id order)
   status ^{:line 559 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (ord/order-status order)]
  ^{:line 560 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} [^{:line 560 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (->AuditEntry base-id "order" oid "create" actor-id timestamp "pending") ^{:line 561 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (->AuditEntry ^{:line 561 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (+ base-id 1) "order" oid "update" actor-id ^{:line 562 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (+ timestamp 1) status)]))

^{:line 565 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (defn audit-shipment-lifecycle [base-id shipment actor-id timestamp]
  ^{:line 568 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (let [sid ^{:line 568 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (ship/shipment-id shipment)
   status ^{:line 569 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (ship/shipment-status shipment)]
  ^{:line 570 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} [^{:line 570 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (->AuditEntry base-id "shipment" sid "create" actor-id timestamp "pending") ^{:line 571 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (->AuditEntry ^{:line 571 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (+ base-id 1) "shipment" sid "update" actor-id ^{:line 572 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (+ timestamp 1) status)]))

^{:line 575 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (defn audit-invoice-lifecycle [base-id invoice actor-id timestamp]
  ^{:line 578 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (let [iid ^{:line 578 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (bill/invoice-id invoice)
   status ^{:line 579 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (bill/invoice-status invoice)]
  ^{:line 580 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} [^{:line 580 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (->AuditEntry base-id "invoice" iid "create" actor-id timestamp "unpaid") ^{:line 581 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (->AuditEntry ^{:line 581 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (+ base-id 1) "invoice" iid "update" actor-id ^{:line 582 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (+ timestamp 1) status)]))

^{:line 589 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (defn check-order-invoice-coverage [orders invoices]
  ^{:line 591 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (mapv ^{:line 591 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (fn [o] ^{:line 592 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (let [oid ^{:line 592 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (ord/order-id o)
   matching ^{:line 593 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (bill/invoices-for-order invoices oid)
   passed ^{:line 594 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (> ^{:line 594 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (count matching) 0)
   detail ^{:line 595 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (if passed ^{:line 596 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (str "Order #" oid " has invoice") ^{:line 597 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (str "Order #" oid " missing invoice"))]
  ^{:line 598 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (->ComplianceCheck 0 "order-invoice-coverage" oid passed detail 0))) orders))

^{:line 603 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (defn check-shipment-carrier-valid [shipments carriers]
  ^{:line 605 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (mapv ^{:line 605 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (fn [s] ^{:line 606 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (let [cid ^{:line 606 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (ship/shipment-carrier-id s)
   carrier ^{:line 607 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (ship/find-carrier-by-id carriers cid)
   passed ^{:line 608 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (not ^{:line 608 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (nil? carrier))
   detail ^{:line 609 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (if passed ^{:line 610 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (str "Carrier #" cid " exists") ^{:line 611 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (str "Carrier #" cid " not found"))]
  ^{:line 612 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (->ComplianceCheck 0 "shipment-carrier-valid" ^{:line 613 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (ship/shipment-id s) passed detail 0))) shipments))

^{:line 618 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (defn check-notification-template-valid [notifications templates]
  ^{:line 620 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (mapv ^{:line 620 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (fn [n] ^{:line 621 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (let [tid ^{:line 621 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (notif/notification-template-id n)
   tmpl ^{:line 622 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (notif/find-template-by-id templates tid)
   passed ^{:line 623 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (not ^{:line 623 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (nil? tmpl))
   detail ^{:line 624 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (if passed ^{:line 625 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (str "Template #" tid " exists") ^{:line 626 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (str "Template #" tid " not found"))]
  ^{:line 627 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (->ComplianceCheck 0 "notification-template-valid" ^{:line 628 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (notif/notification-id n) passed detail 0))) notifications))

^{:line 637 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (defn total-system-revenue [payments]
  ^{:line 638 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (bill/total-revenue-collected payments))

^{:line 641 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (defn revenue-vs-shipping [orders shipments]
  ^{:line 642 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (let [rev ^{:line 642 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (ord/total-revenue orders)
   ship-cost ^{:line 643 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (ship/total-shipping-revenue shipments)
   net ^{:line 644 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (- rev ship-cost)
   ship-pct ^{:line 645 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (if ^{:line 645 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (= rev 0) 0 ^{:line 645 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (quot ^{:line 645 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (* ship-cost 100) rev))]
  ^{:line 646 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} {:revenue rev :shipping-cost ship-cost :net-after-shipping net :shipping-pct ship-pct}))

^{:line 652 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (defn revenue-vs-procurement [orders pos]
  ^{:line 653 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (let [rev ^{:line 653 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (ord/total-revenue orders)
   spend ^{:line 654 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (proc/total-procurement-spend pos)
   margin ^{:line 655 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (- rev spend)
   margin-pct ^{:line 656 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (if ^{:line 656 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (= rev 0) 0 ^{:line 656 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (quot ^{:line 656 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (* margin 100) rev))]
  ^{:line 657 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} {:revenue rev :procurement-spend spend :gross-margin margin :margin-pct margin-pct}))

^{:line 663 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (defn revenue-vs-commissions [orders rules employees products]
  ^{:line 665 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (let [rev ^{:line 665 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (ord/total-revenue orders)
   total-comm ^{:line 666 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (reduce ^{:line 667 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (fn [acc e] ^{:line 668 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (+ acc ^{:line 668 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (emp/total-commission rules ^{:line 669 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (emp/employee-id e) orders products))) 0 ^{:line 671 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (emp/active-employees employees))
   comm-pct ^{:line 672 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (if ^{:line 672 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (= rev 0) 0 ^{:line 672 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (quot ^{:line 672 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (* total-comm 100) rev))]
  ^{:line 673 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} {:revenue rev :total-commissions total-comm :commission-pct comm-pct}))

^{:line 682 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (defn inventory-health-check [levels products orders]
  ^{:line 684 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (let [total-value ^{:line 684 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (inv/total-inventory-value levels products)
   low-stock ^{:line 685 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (count ^{:line 685 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (inv/low-stock-items levels))
   out-of-stock ^{:line 686 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (count ^{:line 686 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (inv/out-of-stock-items levels))
   total-items ^{:line 687 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (count levels)
   health-pct ^{:line 688 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (if ^{:line 688 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (= total-items 0) 100 ^{:line 689 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (quot ^{:line 689 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (* ^{:line 689 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (- total-items low-stock) 100) total-items))
   reorder-cost ^{:line 690 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (inv/reorder-cost levels products)]
  ^{:line 691 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} {:total-value total-value :low-stock-count low-stock :out-of-stock-count out-of-stock :total-items total-items :health-pct health-pct :reorder-cost reorder-cost}))

^{:line 703 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (defn customer-health-check [customer orders invoices payments notifications]
  ^{:line 706 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (let [cid ^{:line 706 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (cust/customer-id customer)
   order-count ^{:line 707 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (ord/customer-order-count orders cid)
   total-spend ^{:line 708 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (ord/customer-total-spend orders cid)
   outstanding ^{:line 709 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (bill/customer-outstanding-balance invoices payments cid)
   unpaid-count ^{:line 710 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (bill/customer-unpaid-count invoices cid)
   notif-count ^{:line 711 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (notif/customer-notification-count notifications cid)
   tier ^{:line 712 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (cust/customer-tier customer)]
  ^{:line 713 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} {:customer-id cid :name ^{:line 713 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (cust/customer-name customer) :tier tier :order-count order-count :total-spend total-spend :outstanding-balance outstanding :unpaid-invoices unpaid-count :notification-count notif-count}))

^{:line 727 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (defn promotion-impact-assessment [orders campaigns coupons now]
  ^{:line 730 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (let [total-rev ^{:line 730 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (ord/total-revenue orders)
   total-disc ^{:line 731 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (ord/total-discounts-given orders)
   active-camps ^{:line 732 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (count ^{:line 732 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (promo/active-campaigns campaigns now))
   total-coupon-uses ^{:line 733 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (promo/total-coupon-uses coupons)
   disc-pct ^{:line 734 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (if ^{:line 734 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (= total-rev 0) 0 ^{:line 735 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (quot ^{:line 735 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (* total-disc 100) ^{:line 735 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (+ total-rev total-disc)))]
  ^{:line 736 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} {:total-revenue total-rev :total-discounts total-disc :discount-pct disc-pct :active-campaigns active-camps :total-coupon-uses total-coupon-uses}))

^{:line 747 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (defn employee-audit-trail [entries employee-id employees]
  ^{:line 749 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (let [employee ^{:line 749 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (emp/find-employee-by-id employees employee-id)
   actor-entries ^{:line 750 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (entries-by-actor entries employee-id)
   name ^{:line 751 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (if ^{:line 751 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (nil? employee) "unknown" ^{:line 751 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (emp/employee-name employee))]
  ^{:line 752 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} {:employee-id employee-id :employee-name name :entry-count ^{:line 752 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (count actor-entries) :entries actor-entries}))

^{:line 762 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (defn notification-compliance-check [notifications templates]
  ^{:line 764 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (let [total ^{:line 764 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (count notifications)
   del-rate ^{:line 765 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (notif/delivery-rate-pct notifications)
   sent-cnt ^{:line 766 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (notif/notifications-sent-count notifications)
   failed-cnt ^{:line 767 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (notif/notifications-failed-count notifications)
   avg-time ^{:line 768 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (notif/avg-send-time notifications)]
  ^{:line 769 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} {:total-notifications total :delivery-rate del-rate :sent-count sent-cnt :failed-count failed-cnt :avg-send-time avg-time :healthy ^{:line 769 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (>= del-rate 80)}))

^{:line 781 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (defn audit-dashboard [entries orders invoices payments shipments levels products movements]
  ^{:line 784 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (let [entry-cnt ^{:line 785 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (count entries)
   action-dist ^{:line 786 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (action-distribution entries)
   entity-dist ^{:line 787 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (entity-type-distribution entries)
   rev-recon ^{:line 789 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (reconcile-revenue orders invoices 0 999999999)
   inv-recon ^{:line 792 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (reconcile-inventory levels products movements)
   bill-recon ^{:line 794 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (reconcile-billing-payments invoices payments)]
  ^{:line 795 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} {:audit-entries entry-cnt :action-distribution action-dist :entity-distribution entity-dist :revenue-reconciliation ^{:line 795 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} {:status ^{:line 795 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (reconciliationresult-status rev-recon) :discrepancy ^{:line 795 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (reconciliationresult-discrepancy rev-recon)} :inventory-reconciliation ^{:line 795 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} {:status ^{:line 795 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (reconciliationresult-status inv-recon) :discrepancy ^{:line 795 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (reconciliationresult-discrepancy inv-recon)} :billing-reconciliation ^{:line 795 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} {:status ^{:line 795 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (reconciliationresult-status bill-recon) :discrepancy ^{:line 795 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (reconciliationresult-discrepancy bill-recon)}}))

^{:line 813 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (defn full-compliance-report [orders customers invoices shipments payments]
  ^{:line 816 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (let [order-checks ^{:line 816 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (run-order-checks orders customers)
   invoice-checks ^{:line 817 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (run-invoice-checks invoices orders)
   shipment-checks ^{:line 818 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (run-shipment-checks shipments orders)
   payment-checks ^{:line 819 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (run-payment-checks payments invoices)
   all-checks ^{:line 820 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (into ^{:line 820 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} [] ^{:line 820 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (concat order-checks invoice-checks shipment-checks payment-checks))
   total ^{:line 822 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (count all-checks)
   passed-cnt ^{:line 823 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (count ^{:line 823 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (passed-checks all-checks))
   failed-cnt ^{:line 824 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (count ^{:line 824 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (failed-checks all-checks))
   rate ^{:line 825 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (compliance-pass-rate all-checks)]
  ^{:line 826 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} {:order-checks ^{:line 826 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} {:total ^{:line 826 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (count order-checks) :pass-rate ^{:line 826 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (compliance-pass-rate order-checks)} :invoice-checks ^{:line 826 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} {:total ^{:line 826 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (count invoice-checks) :pass-rate ^{:line 826 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (compliance-pass-rate invoice-checks)} :shipment-checks ^{:line 826 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} {:total ^{:line 826 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (count shipment-checks) :pass-rate ^{:line 826 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (compliance-pass-rate shipment-checks)} :payment-checks ^{:line 826 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} {:total ^{:line 826 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (count payment-checks) :pass-rate ^{:line 826 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (compliance-pass-rate payment-checks)} :overall ^{:line 826 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} {:total-checks total :passed passed-cnt :failed failed-cnt :pass-rate rate}}))

^{:line 845 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (defn system-health-score [orders invoices payments shipments levels products notifications]
  ^{:line 848 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (let [coll-rate ^{:line 849 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (bill/collection-rate-pct invoices payments)
   total-items ^{:line 851 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (count levels)
   low-stock ^{:line 852 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (count ^{:line 852 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (inv/low-stock-items levels))
   inv-health ^{:line 853 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (if ^{:line 853 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (= total-items 0) 100 ^{:line 854 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (quot ^{:line 854 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (* ^{:line 854 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (- total-items low-stock) 100) total-items))
   notif-health ^{:line 856 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (notif/delivery-rate-pct notifications)
   active ^{:line 858 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (ord/active-orders orders)
   active-count ^{:line 859 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (count active)
   shipped-count ^{:line 860 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (count ^{:line 860 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (ship/orders-with-shipments shipments active))
   ship-health ^{:line 861 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (if ^{:line 861 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (= active-count 0) 100 ^{:line 862 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (quot ^{:line 862 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (* shipped-count 100) active-count))
   score ^{:line 865 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (quot ^{:line 865 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (+ ^{:line 865 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (* coll-rate 30) ^{:line 865 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (* inv-health 25) ^{:line 866 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (* notif-health 20) ^{:line 866 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (* ship-health 25)) 100)]
  score))

^{:line 875 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (defn sort-entries-by-timestamp [entries]
  ^{:line 876 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (sort-by ^{:line 876 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (fn [e] ^{:line 876 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (auditentry-timestamp e)) entries))

^{:line 879 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (defn sort-entries-by-id [entries]
  ^{:line 880 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (sort-by auditentry-id entries))

^{:line 888 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (defn entries-with-detail [entries detail]
  ^{:line 889 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (filterv ^{:line 889 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (fn [e] ^{:line 889 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (= ^{:line 889 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (auditentry-detail e) detail)) entries))

^{:line 892 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (defn entries-for-entity-action [entries entity-type action]
  ^{:line 894 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (filterv ^{:line 894 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (fn [e] ^{:line 894 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (and ^{:line 894 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (= ^{:line 894 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (auditentry-entity-type e) entity-type) ^{:line 895 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (= ^{:line 895 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (auditentry-action e) action))) entries))

^{:line 903 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (defn audit-kpi-snapshot [orders invoices payments shipments levels products]
  ^{:line 906 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (let [total-rev ^{:line 906 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (ord/total-revenue orders)
   total-collected ^{:line 907 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (bill/total-revenue-collected payments)
   total-outstanding ^{:line 908 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (bill/total-outstanding invoices payments)
   total-shipping ^{:line 909 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (ship/total-shipping-revenue shipments)
   inventory-value ^{:line 910 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (inv/total-inventory-value levels products)
   order-count ^{:line 911 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (count orders)]
  ^{:line 912 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} {:total-revenue total-rev :total-collected total-collected :total-outstanding total-outstanding :total-shipping total-shipping :inventory-value inventory-value :order-count order-count}))

^{:line 925 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (defn high-value-order-entries [entries orders threshold]
  ^{:line 927 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (let [high-orders ^{:line 927 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (ord/orders-above-total orders threshold)
   high-ids ^{:line 928 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (mapv ^{:line 928 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (fn [o] ^{:line 928 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (ord/order-id o)) high-orders)]
  ^{:line 929 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (filterv ^{:line 929 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (fn [e] ^{:line 930 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (and ^{:line 930 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (= ^{:line 930 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (auditentry-entity-type e) "order") ^{:line 931 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (some ^{:line 931 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (fn [oid] ^{:line 931 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (= ^{:line 931 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (auditentry-entity-id e) oid)) high-ids))) entries)))

^{:line 936 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (defn actors-with-cancellations [entries]
  ^{:line 937 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (let [cancel-entries ^{:line 937 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (entries-by-action entries "cancel")]
  ^{:line 938 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (distinct ^{:line 938 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (mapv auditentry-actor-id cancel-entries))))

^{:line 941 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (defn entity-change-frequency [entries entity-type entity-id]
  ^{:line 943 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (count ^{:line 943 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (entries-for-entity entries entity-type entity-id)))

^{:line 946 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (defn entities-with-high-churn [entries entity-type threshold]
  ^{:line 948 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (let [type-entries ^{:line 948 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (entries-by-entity-type entries entity-type)
   entity-ids ^{:line 949 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (distinct ^{:line 949 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (mapv auditentry-entity-id type-entries))]
  ^{:line 950 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (filterv ^{:line 950 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (fn [eid] ^{:line 951 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (> ^{:line 951 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (entity-change-frequency entries entity-type eid) threshold)) entity-ids)))

^{:line 959 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (defn audit-period-report [entries start end]
  ^{:line 961 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (let [period-entries ^{:line 961 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (entries-in-period entries start end)
   total ^{:line 962 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (count period-entries)
   actors ^{:line 963 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (distinct-actors period-entries)
   creates ^{:line 964 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (count ^{:line 964 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (entries-by-action period-entries "create"))
   updates ^{:line 965 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (count ^{:line 965 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (entries-by-action period-entries "update"))
   cancels ^{:line 966 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (count ^{:line 966 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (entries-by-action period-entries "cancel"))]
  ^{:line 967 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} {:period-start start :period-end end :total-entries total :unique-actors ^{:line 967 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (count actors) :creates creates :updates updates :cancels cancels}))

^{:line 980 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (defn orphan-invoices [invoices orders]
  ^{:line 981 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (filterv ^{:line 981 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (fn [inv] ^{:line 982 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (nil? ^{:line 982 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (ord/find-order-by-id orders ^{:line 982 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (bill/invoice-order-id inv)))) invoices))

^{:line 986 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (defn orphan-shipments [shipments orders]
  ^{:line 987 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (filterv ^{:line 987 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (fn [s] ^{:line 988 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (nil? ^{:line 988 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (ord/find-order-by-id orders ^{:line 988 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (ship/shipment-order-id s)))) shipments))

^{:line 992 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (defn orphan-payments [payments invoices]
  ^{:line 993 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (filterv ^{:line 993 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (fn [p] ^{:line 994 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (nil? ^{:line 994 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (bill/find-invoice-by-id invoices ^{:line 994 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (bill/payment-invoice-id p)))) payments))

^{:line 998 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (defn data-integrity-report [orders invoices payments shipments]
  ^{:line 1000 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (let [orphan-inv ^{:line 1000 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (orphan-invoices invoices orders)
   orphan-ship ^{:line 1001 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (orphan-shipments shipments orders)
   orphan-pay ^{:line 1002 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (orphan-payments payments invoices)
   clean ^{:line 1003 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (and ^{:line 1003 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (= ^{:line 1003 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (count orphan-inv) 0) ^{:line 1004 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (= ^{:line 1004 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (count orphan-ship) 0) ^{:line 1005 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (= ^{:line 1005 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (count orphan-pay) 0))]
  ^{:line 1006 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} {:orphan-invoices ^{:line 1006 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (count orphan-inv) :orphan-shipments ^{:line 1006 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (count orphan-ship) :orphan-payments ^{:line 1006 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e14-pool-run2/audit.rkt"} (count orphan-pay) :data-clean clean}))
