(ns reports
  (:require [catalog :as cat]
            [inventory :as inv]
            [customers :as cust]
            [orders :as ord]))

^{:line 13 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (defn inventory-summary-report [levels products warehouses]
  ^{:line 15 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (mapv ^{:line 15 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (fn [wh] ^{:line 16 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (let [wh-id ^{:line 16 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (inv/warehouse-id wh)
   item-count ^{:line 17 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (inv/warehouse-item-count levels wh-id)
   total-units ^{:line 18 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (inv/warehouse-total-units levels wh-id)
   value ^{:line 19 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (inv/stock-value-at-warehouse levels wh-id products)
   util ^{:line 20 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (inv/warehouse-utilization-pct levels wh)]
  ^{:line 21 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} {:warehouse-name ^{:line 21 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (inv/warehouse-name wh) :location ^{:line 21 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (inv/warehouse-location wh) :item-count item-count :total-units total-units :value value :utilization-pct util})) warehouses))

^{:line 29 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (defn low-stock-report [levels products]
  ^{:line 30 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (let [low ^{:line 30 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (inv/low-stock-items levels)]
  ^{:line 31 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (mapv ^{:line 31 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (fn [sl] ^{:line 32 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (let [prod ^{:line 32 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (cat/find-product-by-id products ^{:line 32 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (inv/stocklevel-product-id sl))
   pname ^{:line 33 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (if ^{:line 33 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (nil? prod) "unknown" ^{:line 33 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (cat/product-name prod))
   qty ^{:line 34 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (inv/stocklevel-quantity sl)
   min-qty ^{:line 35 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (inv/stocklevel-min-quantity sl)]
  ^{:line 36 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} {:product-name pname :product-id ^{:line 36 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (inv/stocklevel-product-id sl) :quantity qty :min-quantity min-qty :deficit ^{:line 36 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (- min-qty qty)})) low)))

^{:line 43 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (defn reorder-report [levels products suppliers]
  ^{:line 44 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (let [needed ^{:line 44 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (inv/reorder-needed levels)]
  ^{:line 45 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (mapv ^{:line 45 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (fn [sl] ^{:line 46 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (let [prod ^{:line 46 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (cat/find-product-by-id products ^{:line 46 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (inv/stocklevel-product-id sl))
   pname ^{:line 47 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (if ^{:line 47 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (nil? prod) "unknown" ^{:line 47 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (cat/product-name prod))
   sup-id ^{:line 48 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (if ^{:line 48 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (nil? prod) 0 ^{:line 48 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (cat/product-supplier-id prod))
   sup ^{:line 49 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (cat/find-supplier-by-id suppliers sup-id)
   sup-name ^{:line 50 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (if ^{:line 50 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (nil? sup) "unknown" ^{:line 50 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (cat/supplier-name sup))
   qty ^{:line 51 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (inv/reorder-quantity sl)
   cost ^{:line 52 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (if ^{:line 52 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (nil? prod) 0 ^{:line 52 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (* qty ^{:line 52 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (cat/product-unit-cost prod)))]
  ^{:line 53 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} {:product-name pname :supplier-name sup-name :reorder-qty qty :estimated-cost cost :lead-time ^{:line 53 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (if ^{:line 53 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (nil? sup) 0 ^{:line 53 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (cat/supplier-lead-time-days sup))})) needed)))

^{:line 62 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (defn sales-summary [orders]
  ^{:line 63 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (let [all-orders orders
   active ^{:line 64 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (ord/active-orders all-orders)
   pending ^{:line 65 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (ord/pending-orders all-orders)]
  ^{:line 66 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} {:total-orders ^{:line 66 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (count all-orders) :active-orders ^{:line 66 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (count active) :pending-orders ^{:line 66 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (count pending) :total-revenue ^{:line 66 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (ord/total-revenue all-orders) :total-tax ^{:line 66 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (ord/total-tax-collected all-orders) :total-discounts ^{:line 66 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (ord/total-discounts-given all-orders) :avg-order-value ^{:line 66 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (ord/avg-order-value all-orders)}))

^{:line 74 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (defn product-sales-report [orders products]
  ^{:line 75 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (mapv ^{:line 75 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (fn [p] ^{:line 76 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (let [pid ^{:line 76 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (cat/product-id p)
   units ^{:line 77 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (ord/product-units-ordered orders pid)
   revenue ^{:line 78 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (ord/product-revenue orders pid)]
  ^{:line 79 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} {:product-name ^{:line 79 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (cat/product-name p) :sku ^{:line 79 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (cat/product-sku p) :units-sold units :revenue revenue :margin-pct ^{:line 79 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (cat/product-margin-pct p)})) ^{:line 84 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (cat/active-products products)))

^{:line 86 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (defn top-products-by-revenue [orders products n]
  ^{:line 87 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (let [report ^{:line 87 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (product-sales-report orders products)
   sorted ^{:line 88 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (reverse ^{:line 88 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (sort-by ^{:line 88 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (fn [r] ^{:line 88 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (:revenue r)) report))]
  ^{:line 89 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (vec ^{:line 89 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (take n sorted))))

^{:line 91 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (defn top-products-by-units [orders products n]
  ^{:line 92 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (let [report ^{:line 92 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (product-sales-report orders products)
   sorted ^{:line 93 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (reverse ^{:line 93 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (sort-by ^{:line 93 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (fn [r] ^{:line 93 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (:units-sold r)) report))]
  ^{:line 94 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (vec ^{:line 94 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (take n sorted))))

^{:line 98 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (defn customer-report [customers orders]
  ^{:line 99 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (mapv ^{:line 99 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (fn [c] ^{:line 100 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (let [cid ^{:line 100 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (cust/customer-id c)
   order-count ^{:line 101 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (ord/customer-order-count orders cid)
   total-spend ^{:line 102 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (ord/customer-total-spend orders cid)
   avg-order ^{:line 103 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (ord/customer-avg-order orders cid)]
  ^{:line 104 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} {:customer-name ^{:line 104 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (cust/customer-name c) :tier ^{:line 104 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (cust/customer-tier c) :order-count order-count :total-spend total-spend :avg-order avg-order})) customers))

^{:line 111 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (defn top-customers-by-spend [customers orders n]
  ^{:line 112 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (let [report ^{:line 112 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (customer-report customers orders)
   sorted ^{:line 113 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (reverse ^{:line 113 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (sort-by ^{:line 113 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (fn [r] ^{:line 113 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (:total-spend r)) report))]
  ^{:line 114 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (vec ^{:line 114 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (take n sorted))))

^{:line 116 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (defn tier-revenue-report [customers orders]
  ^{:line 117 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (let [tiers ^{:line 117 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} ["gold" "silver" "bronze"]]
  ^{:line 118 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (mapv ^{:line 118 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (fn [tier] ^{:line 119 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (let [tier-custs ^{:line 119 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (cust/customers-by-tier customers tier)
   cust-ids ^{:line 120 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (mapv ^{:line 120 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (fn [c] ^{:line 120 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (cust/customer-id c)) tier-custs)
   tier-orders ^{:line 121 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (filterv ^{:line 121 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (fn [o] ^{:line 122 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (some ^{:line 122 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (fn [id] ^{:line 122 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (= ^{:line 122 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (ord/order-customer-id o) id)) cust-ids)) orders)
   revenue ^{:line 126 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (ord/total-revenue tier-orders)]
  ^{:line 127 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} {:tier tier :customer-count ^{:line 127 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (count tier-custs) :order-count ^{:line 127 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (count tier-orders) :revenue revenue})) tiers)))

^{:line 135 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (defn category-performance-report [orders products categories]
  ^{:line 137 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (mapv ^{:line 137 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (fn [c] ^{:line 138 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (let [cat-id ^{:line 138 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (cat/category-id c)
   cat-prods ^{:line 139 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (cat/products-by-category products cat-id)
   revenue ^{:line 140 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (reduce ^{:line 140 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (fn [acc p] ^{:line 141 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (+ acc ^{:line 141 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (ord/product-revenue orders ^{:line 141 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (cat/product-id p)))) 0 cat-prods)
   units ^{:line 143 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (reduce ^{:line 143 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (fn [acc p] ^{:line 144 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (+ acc ^{:line 144 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (ord/product-units-ordered orders ^{:line 144 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (cat/product-id p)))) 0 cat-prods)]
  ^{:line 146 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} {:category-name ^{:line 146 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (cat/category-name c) :product-count ^{:line 146 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (count cat-prods) :total-revenue revenue :total-units units :avg-margin ^{:line 146 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (cat/category-avg-margin products cat-id)})) categories))

^{:line 155 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (defn supplier-performance-report [orders products suppliers]
  ^{:line 157 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (mapv ^{:line 157 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (fn [s] ^{:line 158 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (let [sup-id ^{:line 158 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (cat/supplier-id s)
   sup-prods ^{:line 159 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (cat/products-by-supplier products sup-id)
   revenue ^{:line 160 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (reduce ^{:line 160 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (fn [acc p] ^{:line 161 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (+ acc ^{:line 161 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (ord/product-revenue orders ^{:line 161 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (cat/product-id p)))) 0 sup-prods)
   units ^{:line 163 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (reduce ^{:line 163 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (fn [acc p] ^{:line 164 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (+ acc ^{:line 164 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (ord/product-units-ordered orders ^{:line 164 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (cat/product-id p)))) 0 sup-prods)]
  ^{:line 166 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} {:supplier-name ^{:line 166 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (cat/supplier-name s) :product-count ^{:line 166 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (count sup-prods) :total-revenue revenue :total-units units :lead-time ^{:line 166 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (cat/supplier-lead-time-days s)})) suppliers))

^{:line 175 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (defn fulfillment-report [orders levels]
  ^{:line 176 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (let [pending ^{:line 176 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (ord/pending-orders orders)]
  ^{:line 177 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (mapv ^{:line 177 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (fn [o] ^{:line 178 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (let [can-fulfill ^{:line 178 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (ord/can-fulfill-order? levels o)
   unfulfillable ^{:line 179 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (ord/unfulfillable-lines levels o)]
  ^{:line 180 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} {:order-id ^{:line 180 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (ord/order-id o) :customer-id ^{:line 180 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (ord/order-customer-id o) :total ^{:line 180 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (ord/order-total o) :can-fulfill can-fulfill :unfulfillable-line-count ^{:line 180 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (count unfulfillable)})) pending)))

^{:line 187 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (defn fulfillment-rate [orders levels]
  ^{:line 188 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (let [pending ^{:line 188 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (ord/pending-orders orders)
   cnt ^{:line 189 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (count pending)]
  ^{:line 190 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (if ^{:line 190 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (= cnt 0) 100 ^{:line 191 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (let [fulfillable ^{:line 191 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (count ^{:line 191 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (filterv ^{:line 191 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (fn [o] ^{:line 191 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (ord/can-fulfill-order? levels o)) pending))]
  ^{:line 193 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (quot ^{:line 193 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (* fulfillable 100) cnt)))))

^{:line 197 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (defn dashboard [products suppliers categories levels warehouses customers orders]
  ^{:line 200 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} {:catalog ^{:line 200 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} {:total-products ^{:line 200 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (count products) :active-products ^{:line 200 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (count ^{:line 200 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (cat/active-products products)) :total-value ^{:line 200 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (cat/total-catalog-value products) :avg-price ^{:line 200 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (cat/avg-unit-price products)} :inventory ^{:line 200 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} {:total-value ^{:line 200 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (inv/total-inventory-value levels products) :retail-value ^{:line 200 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (inv/stock-retail-value levels products) :low-stock-count ^{:line 200 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (count ^{:line 200 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (inv/low-stock-items levels)) :reorder-cost ^{:line 200 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (inv/reorder-cost levels products)} :customers ^{:line 200 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} {:total-count ^{:line 200 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (cust/total-customer-count customers) :tier-counts ^{:line 200 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (cust/count-by-tier customers)} :orders ^{:line 200 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} {:total-orders ^{:line 200 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (count orders) :total-revenue ^{:line 200 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (ord/total-revenue orders) :avg-order-value ^{:line 200 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (ord/avg-order-value orders) :fulfillment-rate ^{:line 200 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (fulfillment-rate orders levels)}})

^{:line 217 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (defn format-report-line [label value]
  ^{:line 218 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (str label ": " ^{:line 218 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (cat/format-price value)))

^{:line 220 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (defn format-report-header [title]
  ^{:line 221 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (str "=== " title " ==="))

^{:line 223 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (defn print-inventory-summary [levels products warehouses]
  ^{:line 225 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (let [report ^{:line 225 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (inventory-summary-report levels products warehouses)]
  ^{:line 226 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (do
  ^{:line 226 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (println ^{:line 226 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (format-report-header "Inventory Summary"))
  ^{:line 227 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (doseq [r report]
  ^{:line 228 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (println ^{:line 228 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (str ^{:line 228 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (:warehouse-name r) " (" ^{:line 228 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (:location r) ")" " | Items: " ^{:line 229 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (:item-count r) " | Units: " ^{:line 230 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (:total-units r) " | Value: " ^{:line 231 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (cat/format-price ^{:line 231 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (:value r)) " | Util: " ^{:line 232 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (:utilization-pct r) "%")))
  report)))

^{:line 235 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (defn print-sales-summary [orders]
  ^{:line 236 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (let [report ^{:line 236 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (sales-summary orders)]
  ^{:line 237 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (do
  ^{:line 237 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (println ^{:line 237 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (format-report-header "Sales Summary"))
  ^{:line 238 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (println ^{:line 238 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (str "Orders: " ^{:line 238 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (:total-orders report)))
  ^{:line 239 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (println ^{:line 239 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (format-report-line "Revenue" ^{:line 239 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (:total-revenue report)))
  ^{:line 240 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (println ^{:line 240 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (format-report-line "Tax" ^{:line 240 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (:total-tax report)))
  ^{:line 241 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (println ^{:line 241 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (format-report-line "Discounts" ^{:line 241 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (:total-discounts report)))
  report)))

^{:line 246 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (defn product-profitability [orders products]
  ^{:line 247 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (mapv ^{:line 247 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (fn [p] ^{:line 248 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (let [pid ^{:line 248 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (cat/product-id p)
   revenue ^{:line 249 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (ord/product-revenue orders pid)
   units ^{:line 250 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (ord/product-units-ordered orders pid)
   cost-of-goods ^{:line 251 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (* units ^{:line 251 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (cat/product-unit-cost p))
   gross-profit ^{:line 252 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (- revenue cost-of-goods)
   margin ^{:line 253 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (if ^{:line 253 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (= revenue 0) 0 ^{:line 253 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (quot ^{:line 253 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (* gross-profit 100) revenue))]
  ^{:line 254 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} {:product-name ^{:line 254 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (cat/product-name p) :revenue revenue :cost-of-goods cost-of-goods :gross-profit gross-profit :margin-pct margin})) ^{:line 259 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (cat/active-products products)))

^{:line 261 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (defn most-profitable-products [orders products n]
  ^{:line 262 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (let [report ^{:line 262 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (product-profitability orders products)
   sorted ^{:line 263 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (reverse ^{:line 263 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (sort-by ^{:line 263 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (fn [r] ^{:line 263 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (:gross-profit r)) report))]
  ^{:line 264 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (vec ^{:line 264 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (take n sorted))))

^{:line 266 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (defn unprofitable-products [orders products]
  ^{:line 267 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (filterv ^{:line 267 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (fn [r] ^{:line 267 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (<= ^{:line 267 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (:gross-profit r) 0)) ^{:line 268 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (product-profitability orders products)))

^{:line 272 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (defn customer-lifetime-value [c orders current-year]
  ^{:line 273 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (let [cid ^{:line 273 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (cust/customer-id c)
   total-spend ^{:line 274 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (ord/customer-total-spend orders cid)
   tenure ^{:line 275 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (cust/customer-tenure c current-year)
   annual-value ^{:line 276 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (if ^{:line 276 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (= tenure 0) total-spend ^{:line 276 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (quot total-spend tenure))]
  ^{:line 277 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} {:customer-name ^{:line 277 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (cust/customer-name c) :tier ^{:line 277 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (cust/customer-tier c) :total-spend total-spend :tenure-years tenure :annual-value annual-value}))

^{:line 283 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (defn clv-report [customers orders current-year]
  ^{:line 284 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (mapv ^{:line 284 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (fn [c] ^{:line 284 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (customer-lifetime-value c orders current-year)) customers))

^{:line 286 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (defn top-clv-customers [customers orders current-year n]
  ^{:line 288 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (let [report ^{:line 288 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (clv-report customers orders current-year)
   sorted ^{:line 289 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (reverse ^{:line 289 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (sort-by ^{:line 289 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (fn [r] ^{:line 289 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (:annual-value r)) report))]
  ^{:line 290 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (vec ^{:line 290 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (take n sorted))))

^{:line 294 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (defn period-comparison [orders p1-start p1-end p2-start p2-end]
  ^{:line 296 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (let [p1-orders ^{:line 296 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (ord/orders-in-period orders p1-start p1-end)
   p2-orders ^{:line 297 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (ord/orders-in-period orders p2-start p2-end)
   p1-rev ^{:line 298 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (ord/total-revenue p2-orders)
   p2-rev ^{:line 299 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (ord/total-revenue p2-orders)
   rev-change ^{:line 300 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (- p2-rev p1-rev)
   rev-change-pct ^{:line 301 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (if ^{:line 301 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (= p1-rev 0) 0 ^{:line 301 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (quot ^{:line 301 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (* rev-change 100) p1-rev))]
  ^{:line 302 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} {:period1-revenue p1-rev :period1-orders ^{:line 302 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (count p1-orders) :period2-revenue p2-rev :period2-orders ^{:line 302 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (count p2-orders) :revenue-change rev-change :revenue-change-pct rev-change-pct}))

^{:line 311 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (defn inventory-turnover [orders levels products]
  ^{:line 312 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (let [total-cogs ^{:line 312 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (reduce ^{:line 312 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (fn [acc p] ^{:line 313 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (let [units ^{:line 313 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (ord/product-units-ordered orders ^{:line 313 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (cat/product-id p))]
  ^{:line 314 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (+ acc ^{:line 314 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (* units ^{:line 314 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (cat/product-unit-cost p))))) 0 products)
   avg-inv-value ^{:line 316 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (inv/total-inventory-value levels products)]
  ^{:line 317 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} {:cost-of-goods-sold total-cogs :avg-inventory-value avg-inv-value :turnover-ratio ^{:line 317 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (if ^{:line 317 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (= avg-inv-value 0) 0 ^{:line 317 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (quot ^{:line 317 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (* total-cogs 100) avg-inv-value))}))

^{:line 323 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (defn product-360-report [p orders levels]
  ^{:line 324 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (let [pid ^{:line 324 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (cat/product-id p)
   units-sold ^{:line 325 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (ord/product-units-ordered orders pid)
   revenue ^{:line 326 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (ord/product-revenue orders pid)
   stock-qty ^{:line 327 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (inv/total-stock-for-product levels pid)
   margin ^{:line 328 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (cat/product-margin p)
   margin-pct ^{:line 329 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (cat/product-margin-pct p)]
  ^{:line 330 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} {:name ^{:line 330 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (cat/product-name p) :sku ^{:line 330 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (cat/product-sku p) :price ^{:line 330 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (cat/product-unit-price p) :cost ^{:line 330 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (cat/product-unit-cost p) :margin margin :margin-pct margin-pct :units-sold units-sold :revenue revenue :stock-on-hand stock-qty :active ^{:line 330 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (cat/product-active p)}))

^{:line 341 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (defn full-product-report [products orders levels]
  ^{:line 342 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (mapv ^{:line 342 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (fn [p] ^{:line 342 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (product-360-report p orders levels)) products))

^{:line 346 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (defn executive-summary [products suppliers categories levels warehouses customers orders]
  ^{:line 349 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (let [dash ^{:line 349 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (dashboard products suppliers categories levels warehouses customers orders)
   top-prods ^{:line 350 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (top-products-by-revenue orders products 3)
   top-custs ^{:line 351 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (top-customers-by-spend customers orders 3)
   fulfill ^{:line 352 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (fulfillment-rate orders levels)]
  ^{:line 353 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} {:dashboard dash :top-products ^{:line 353 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (mapv ^{:line 353 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (fn [r] ^{:line 353 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (:product-name r)) top-prods) :top-customers ^{:line 353 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (mapv ^{:line 353 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (fn [r] ^{:line 353 :file "/home/tom/code/beagle/experiments/e8-scaled/trials/e13-reactive-run1/reports.rkt"} (:customer-name r)) top-custs) :fulfillment-rate fulfill}))
